//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 11:26:57 a.m. on Tuesday, 28 March 2006
//
//	Generated for file: MenuMate.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		".MenuMate"
//
//	Palm App Version:		"4.0.0.4"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainSeatButton                            1001	//(Left Origin = 100, Top Origin = 17, Width = 40, Height = 15, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Bold)
#define MainSeatdownButton                        1013	//(Left Origin = 80, Top Origin = 17, Width = 20, Height = 15, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define MainSeatupButton                          1014	//(Left Origin = 140, Top Origin = 17, Width = 20, Height = 15, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define MainHappyHourButton                       1015	//(Left Origin = 86, Top Origin = 0, Width = 9, Height = 12, Usable = 0, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Bold)
#define MainDrinksButton                          1019	//(Left Origin = 97, Top Origin = 0, Width = 16, Height = 16, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define MainOverviewButton                        1021	//(Left Origin = 70, Top Origin = 0, Width = 16, Height = 16, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define MainTableButton                           1022	//(Left Origin = 20, Top Origin = 17, Width = 40, Height = 15, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define MainTableupButton                         1032	//(Left Origin = 60, Top Origin = 17, Width = 20, Height = 15, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define MainTabledownButton                       1033	//(Left Origin = 0, Top Origin = 17, Width = 20, Height = 15, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define MainDrinksBitMap                          1	//(Left Origin = 97, Top Origin = 0, Bitmap Resource ID = 1, Usable = 0)
#define MainMealsBitMap                           2	//(Left Origin = 97, Top Origin = 0, Bitmap Resource ID = 2, Usable = 1)
#define MainToggelviewBitMap                      15	//(Left Origin = 70, Top Origin = 0, Bitmap Resource ID = 15, Usable = 1)
#define MainUnnamed1006Label                      1006	//(Left Origin = 153, Top Origin = 19, Usable = 1, Font = Symbol 11)
#define MainTablenoLabel                          1009	//(Left Origin = 9, Top Origin = 19, Usable = 1, Font = Bold)
#define MainPriceLabel                            1010	//(Left Origin = 7, Top Origin = 35, Usable = 1, Font = Large)
#define MainUnnamed1011Label                      1011	//(Left Origin = 82, Top Origin = 19, Usable = 1, Font = Symbol 11)
#define MainSeatnoLabel                           1012	//(Left Origin = 108, Top Origin = 19, Usable = 1, Font = Bold)
#define MainUnnamed1030Label                      1030	//(Left Origin = 0, Top Origin = 19, Usable = 1, Font = Symbol 11)
#define MainUnnamed1031Label                      1031	//(Left Origin = 71, Top Origin = 19, Usable = 1, Font = Symbol 11)
#define MainDishesList                            1016	//(Left Origin = 8, Top Origin = 8, Width = 140, Usable = 0, Font = Standard, Visible Items = 3)
#define MainStaffPopTrigger                       1007	//(Left Origin = 117, Top Origin = 0, Width = 43, Height = 13, Usable = 1, Anchor Left = 1, Font = Bold, List ID = 1008)
#define MainScrollUpRepeating                     1018	//(Left Origin = 146, Top Origin = 138, Width = 14, Height = 11, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol 7)
#define MainScrollDownRepeating                   1020	//(Left Origin = 146, Top Origin = 149, Width = 14, Height = 11, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol 7)
#define MainOrderTable                            1005	//(Left Origin = 0, Top Origin = 34, Width = 145, Height = 126, Editable = 1, Rows = 11)

//	Resource: tFRM 1100
#define AboutMenuMateForm                         1100	//(Left Origin = 2, Top Origin = 46, Width = 156, Height = 112, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1107, Menu Bar ID = 0, Default Button ID = 1105)
#define AboutMenuMateOKButton                     1105	//(Left Origin = 10, Top Origin = 95, Width = 37, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutMenuMateCompanyLogoBitMap            1110	//(Left Origin = 90, Top Origin = 25, Bitmap Resource ID = 1110, Usable = 1)
#define AboutMenuMateCopyrightLabel               1102	//(Left Origin = 10, Top Origin = 58, Usable = 1, Font = Standard)
#define AboutMenuMateApplNameLabel                1103	//(Left Origin = 10, Top Origin = 25, Usable = 1, Font = Bold)
#define AboutMenuMateVersionLabel                 1104	//(Left Origin = 10, Top Origin = 40, Usable = 1, Font = Bold)
#define AboutMenuMateGregorLabel                  1106	//(Left Origin = 10, Top Origin = 79, Usable = 1, Font = Standard)
#define AboutMenuMateVersionNumLabel              1107	//(Left Origin = 34, Top Origin = 40, Usable = 1, Font = Bold)
#define AboutMenuMateUnnamed1108Label             1108	//(Left Origin = 9, Top Origin = 69, Usable = 1, Font = Standard)

//	Resource: tFRM 1400
#define SeatForm                                  1400	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define SeatOkayButton                            1401	//(Left Origin = 10, Top Origin = 135, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define SeatNewNameButton                         1406	//(Left Origin = 10, Top Origin = 73, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define SeatActiveButton                          1407	//(Left Origin = 10, Top Origin = 50, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define SeatZeroButton                            1411	//(Left Origin = 71, Top Origin = 135, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define SeatOneButton                             1412	//(Left Origin = 71, Top Origin = 114, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define SeatTwoButton                             1413	//(Left Origin = 100, Top Origin = 114, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define SeatThreeButton                           1414	//(Left Origin = 128, Top Origin = 114, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define SeatOverviewButton                        1415	//(Left Origin = 68, Top Origin = 0, Width = 20, Height = 16, Usable = 0, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define SeatFourButton                            1416	//(Left Origin = 72, Top Origin = 93, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define SeatFiveButton                            1417	//(Left Origin = 100, Top Origin = 93, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define SeatSixButton                             1418	//(Left Origin = 128, Top Origin = 93, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define SeatSevenButton                           1419	//(Left Origin = 72, Top Origin = 72, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define SeatEightButton                           1420	//(Left Origin = 100, Top Origin = 72, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define SeatNineButton                            1421	//(Left Origin = 128, Top Origin = 72, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define SeatClearButton                           1422	//(Left Origin = 128, Top Origin = 135, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define SeatToggleviewBitMap                      15	//(Left Origin = 70, Top Origin = 0, Bitmap Resource ID = 15, Usable = 0)
#define SeatSeatnoLabel                           1405	//(Left Origin = 115, Top Origin = 51, Usable = 1, Font = Large)
#define SeatPriceLabel                            1410	//(Left Origin = 10, Top Origin = 94, Usable = 0, Font = Bold)
#define SeatNamesList                             1404	//(Left Origin = 13, Top Origin = 18, Width = 130, Usable = 0, Font = Standard, Visible Items = 12)
#define SeatSeatNoPushButton                      1403	//(Left Origin = 72, Top Origin = 49, Width = 78, Height = 13, Usable = 1, Group ID = 1, Font = Bold)
#define SeatNamePopTrigger                        1402	//(Left Origin = 8, Top Origin = 25, Width = 144, Height = 13, Usable = 1, Anchor Left = 1, Font = Bold, List ID = 0)
#define SeatGroupID                               1

//	Resource: tFRM 1600
#define TableForm                                 1600	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1600, Default Button ID = 1601)
#define TableOkayButton                           1601	//(Left Origin = 4, Top Origin = 140, Width = 55, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define TableMenuMateButton                       1604	//(Left Origin = 2, Top Origin = 20, Width = 59, Height = 34, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define TableCallAwayButton                       1607	//(Left Origin = 4, Top Origin = 119, Width = 55, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define TableActiveButton                         1610	//(Left Origin = 4, Top Origin = 60, Width = 55, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define TableHappyHourButton                      1613	//(Left Origin = 86, Top Origin = 0, Width = 9, Height = 12, Usable = 0, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Bold)
#define TableOverviewButton                       1616	//(Left Origin = 68, Top Origin = 0, Width = 16, Height = 16, Usable = 0, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define TableCashButton                           1617	//(Left Origin = 4, Top Origin = 98, Width = 55, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define TableZeroButton                           1618	//(Left Origin = 71, Top Origin = 140, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define TableOneButton                            1619	//(Left Origin = 71, Top Origin = 119, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define TableTwoButton                            1620	//(Left Origin = 100, Top Origin = 119, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define TableThreeButton                          1621	//(Left Origin = 128, Top Origin = 119, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define TableFourButton                           1622	//(Left Origin = 72, Top Origin = 98, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define TableFiveButton                           1623	//(Left Origin = 100, Top Origin = 98, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define TableSixButton                            1624	//(Left Origin = 128, Top Origin = 98, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define TableSevenButton                          1625	//(Left Origin = 72, Top Origin = 77, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define TableEightButton                          1626	//(Left Origin = 100, Top Origin = 77, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define TableNineButton                           1627	//(Left Origin = 128, Top Origin = 77, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define TableClearButton                          1628	//(Left Origin = 128, Top Origin = 140, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define TableToggleviewBitMap                     15	//(Left Origin = 70, Top Origin = 0, Bitmap Resource ID = 15, Usable = 0)
#define TableMenuMateNameLabel                    1603	//(Left Origin = 5, Top Origin = 29, Usable = 1, Font = Bold 12)
#define TablePriceLabel                           1609	//(Left Origin = 5, Top Origin = 77, Usable = 0, Font = Bold)
#define TableNamesList                            1605	//(Left Origin = 15, Top Origin = 17, Width = 130, Usable = 0, Font = Standard, Visible Items = 12)
#define TableTableNoPushButton                    1602	//(Left Origin = 72, Top Origin = 24, Width = 78, Height = 13, Usable = 1, Group ID = 1, Font = Bold)
#define TableGuestsNoPushButton                   1611	//(Left Origin = 72, Top Origin = 40, Width = 78, Height = 13, Usable = 0, Group ID = 1, Font = Bold)
#define TableNamePopTrigger                       1606	//(Left Origin = 67, Top Origin = 58, Width = 93, Height = 13, Usable = 1, Anchor Left = 1, Font = Bold, List ID = 0)
#define TableStaffPopTrigger                      1608	//(Left Origin = 117, Top Origin = 0, Width = 43, Height = 13, Usable = 1, Anchor Left = 1, Font = Bold, List ID = 0)
#define TableGroupID                              1

//	Resource: tFRM 1300
#define DetailsForm                               1300	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1307, Menu Bar ID = 0, Default Button ID = 0)
#define DetailsAttachNoteButton                   1301	//(Left Origin = 72, Top Origin = 33, Width = 82, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define DetailsOkayButton                         1302	//(Left Origin = 4, Top Origin = 140, Width = 37, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define DetailsServeButton                        1304	//(Left Origin = 4, Top Origin = 33, Width = 64, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define DetailsOptionsMinusButton                 1305	//(Left Origin = 114, Top Origin = 15, Width = 37, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define DetailsOptionsPlusButton                  1307	//(Left Origin = 4, Top Origin = 15, Width = 37, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define DetailsPriceAdjButton                     1308	//(Left Origin = 4, Top Origin = 74, Width = 37, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define DetailsLinkedItemsButton                  1315	//(Left Origin = 4, Top Origin = 96, Width = 37, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define DetailsDeleteButton                       1317	//(Left Origin = 4, Top Origin = 52, Width = 37, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define DetailsCopyButton                         1318	//(Left Origin = 4, Top Origin = 118, Width = 37, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define DetailsNipsLabel                          1310	//(Left Origin = 55, Top Origin = 141, Usable = 0, Font = Bold)
#define DetailsOptionsLabel                       1316	//(Left Origin = 56, Top Origin = 15, Usable = 1, Font = Bold)
#define DetailsOptionsList                        1303	//(Left Origin = 9, Top Origin = 32, Width = 140, Usable = 0, Font = Standard, Visible Items = 20)
#define DetailsOptionsSelectedList                1306	//(Left Origin = 46, Top Origin = 53, Width = 108, Usable = 0, Font = Standard, Visible Items = 6)
#define DetailsNips1PushButton                    1311	//(Left Origin = 87, Top Origin = 142, Width = 14, Height = 9, Usable = 0, Group ID = 2, Font = Bold)
#define DetailsNips2PushButton                    1312	//(Left Origin = 102, Top Origin = 142, Width = 14, Height = 9, Usable = 0, Group ID = 2, Font = Bold)
#define DetailsNips3PushButton                    1313	//(Left Origin = 117, Top Origin = 142, Width = 14, Height = 9, Usable = 0, Group ID = 2, Font = Bold)
#define DetailsNips4PushButton                    1314	//(Left Origin = 132, Top Origin = 142, Width = 14, Height = 9, Usable = 0, Group ID = 2, Font = Bold)
#define DetailsSizePopTrigger                     1309	//(Left Origin = 53, Top Origin = 127, Width = 100, Height = 12, Usable = 0, Anchor Left = 1, Font = Bold, List ID = 0)
#define DetailsGroupID                            2

//	Resource: tFRM 1500
#define EditLineForm                              1500	//(Left Origin = 2, Top Origin = 60, Width = 156, Height = 98, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 1)
#define EditLineOkayButton                        1501	//(Left Origin = 10, Top Origin = 80, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define EditLineCancelButton                      1502	//(Left Origin = 60, Top Origin = 80, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define EditLineRecentButton                      1504	//(Left Origin = 10, Top Origin = 18, Width = 96, Height = 12, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Bold)
#define EditLineRecentPopIconBitMap               17	//(Left Origin = 7, Top Origin = 15, Bitmap Resource ID = 17, Usable = 1)
#define EditLineNoteField                         1503	//(Left Origin = 11, Top Origin = 35, Width = 140, Height = 36, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold, Auto Shift = 1, Has Scroll Bar = 0, Numeric = 0)
#define EditLineRecentList                        1506	//(Left Origin = 19, Top Origin = 13, Width = 120, Usable = 0, Font = Standard, Visible Items = 5)

//	Resource: tFRM 1900
#define BeamingForm                               1900	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define BeamingThinkingBitMap                     4	//(Left Origin = 69, Top Origin = 52, Bitmap Resource ID = 4, Usable = 1)
#define BeamingPleaseWaitLabel                    1902	//(Left Origin = 47, Top Origin = 93, Usable = 1, Font = Bold)
#define BeamingRcvd1Label                         1904	//(Left Origin = 132, Top Origin = 13, Usable = 1, Font = Standard)
#define BeamingRcvd2Label                         1905	//(Left Origin = 132, Top Origin = 25, Usable = 1, Font = Standard)
#define BeamingRcvd3Label                         1906	//(Left Origin = 132, Top Origin = 37, Usable = 1, Font = Standard)
#define BeamingRcvd4Label                         1907	//(Left Origin = 132, Top Origin = 50, Usable = 1, Font = Standard)
#define BeamingRcvd5Label                         1908	//(Left Origin = 132, Top Origin = 62, Usable = 1, Font = Standard)
#define BeamingSent1Label                         1909	//(Left Origin = 9, Top Origin = 13, Usable = 1, Font = Standard)
#define BeamingSent2Label                         1910	//(Left Origin = 9, Top Origin = 25, Usable = 1, Font = Standard)
#define BeamingSent3Label                         1911	//(Left Origin = 9, Top Origin = 37, Usable = 1, Font = Standard)
#define BeamingSent4Label                         1912	//(Left Origin = 9, Top Origin = 49, Usable = 1, Font = Standard)
#define BeamingSent5Label                         1913	//(Left Origin = 9, Top Origin = 61, Usable = 1, Font = Standard)
#define BeamingSentSeq1Label                      1914	//(Left Origin = 38, Top Origin = 13, Usable = 1, Font = Standard)
#define BeamingRcvdSeq1Label                      1915	//(Left Origin = 108, Top Origin = 13, Usable = 1, Font = Standard)
#define BeamingSentSeq2Label                      1916	//(Left Origin = 38, Top Origin = 25, Usable = 1, Font = Standard)
#define BeamingSentSeq3Label                      1917	//(Left Origin = 38, Top Origin = 37, Usable = 1, Font = Standard)
#define BeamingSentSeq4Label                      1918	//(Left Origin = 38, Top Origin = 49, Usable = 1, Font = Standard)
#define BeamingSentSeq5Label                      1919	//(Left Origin = 38, Top Origin = 61, Usable = 1, Font = Standard)
#define BeamingRcvdSeq2Label                      1920	//(Left Origin = 108, Top Origin = 25, Usable = 1, Font = Standard)
#define BeamingRcvdSeq3Label                      1921	//(Left Origin = 108, Top Origin = 37, Usable = 1, Font = Standard)
#define BeamingRcvdSeq4Label                      1922	//(Left Origin = 108, Top Origin = 50, Usable = 1, Font = Standard)
#define BeamingRcvdSeq5Label                      1923	//(Left Origin = 108, Top Origin = 62, Usable = 1, Font = Standard)
#define BeamingPacket1Label                       1924	//(Left Origin = 5, Top Origin = 105, Usable = 1, Font = Standard)
#define BeamingPacket2Label                       1925	//(Left Origin = 5, Top Origin = 116, Usable = 1, Font = Standard)
#define BeamingPacket3Label                       1926	//(Left Origin = 5, Top Origin = 127, Usable = 1, Font = Standard)
#define BeamingPacket4Label                       1927	//(Left Origin = 5, Top Origin = 138, Usable = 1, Font = Standard)
#define BeamingPacketsToWriteLabel                1928	//(Left Origin = 66, Top Origin = 13, Usable = 1, Font = Standard)
#define BeamingPacketsToReadLabel                 1929	//(Left Origin = 81, Top Origin = 27, Usable = 1, Font = Standard)
#define BeamingThinkingLabel                      1930	//(Left Origin = 50, Top Origin = 73, Usable = 0, Font = Bold)
#define BeamingBluetoothLabel                     1931	//(Left Origin = 20, Top Origin = 73, Usable = 1, Font = Bold)
#define BeamingBtDevicesList                      1932	//(Left Origin = 8, Top Origin = 20, Width = 140, Usable = 0, Font = Standard, Visible Items = 3)

//	Resource: tFRM 2000
#define DebugDataForm                             2000	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 1100, Default Button ID = 0)
#define DebugDataOkayButton                       2001	//(Left Origin = 116, Top Origin = 136, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DebugDataLogDBButton                      2034	//(Left Origin = 116, Top Origin = 115, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DebugDataOrdersLabel                      2002	//(Left Origin = 9, Top Origin = 27, Usable = 1, Font = Standard)
#define DebugDataNumOrderRecordsLabel             2003	//(Left Origin = 60, Top Origin = 15, Usable = 1, Font = Standard)
#define DebugDataDataSizeLabel                    2004	//(Left Origin = 87, Top Origin = 37, Usable = 1, Font = Standard)
#define DebugDataTotalSizeLabel                   2005	//(Left Origin = 87, Top Origin = 47, Usable = 1, Font = Standard)
#define DebugDataDataLabel                        2006	//(Left Origin = 130, Top Origin = 37, Usable = 1, Font = Standard)
#define DebugDataTotalLabel                       2007	//(Left Origin = 130, Top Origin = 47, Usable = 1, Font = Standard)
#define DebugDataFreeMemoryLabel                  2008	//(Left Origin = 5, Top Origin = 59, Usable = 1, Font = Bold)
#define DebugDataMemoryLabel                      2009	//(Left Origin = 81, Top Origin = 59, Usable = 1, Font = Standard)
#define DebugDataOrdersDBLabel                    2010	//(Left Origin = 5, Top Origin = 15, Usable = 1, Font = Bold)
#define DebugDataStaffIDLabel                     2011	//(Left Origin = 5, Top Origin = 71, Usable = 1, Font = Bold)
#define DebugDataStaffIDNumberLabel               2012	//(Left Origin = 81, Top Origin = 71, Usable = 1, Font = Standard)
#define DebugDataTransactionLabel                 2013	//(Left Origin = 4, Top Origin = 100, Usable = 1, Font = Bold)
#define DebugDataTransactionNumberLabel           2014	//(Left Origin = 81, Top Origin = 100, Usable = 1, Font = Standard)
#define DebugDataMenuSyncLabel                    2015	//(Left Origin = 5, Top Origin = 120, Usable = 1, Font = Bold)
#define DebugDataMenuSyncNumberLabel              2016	//(Left Origin = 81, Top Origin = 120, Usable = 1, Font = Standard)
#define DebugDataLogOffLabel                      2017	//(Left Origin = 5, Top Origin = 90, Usable = 1, Font = Bold)
#define DebugDataLogOffMinsLabel                  2018	//(Left Origin = 81, Top Origin = 90, Usable = 1, Font = Standard)
#define DebugDataInfoSyncLabel                    2019	//(Left Origin = 5, Top Origin = 110, Usable = 1, Font = Bold)
#define DebugDataInfoSyncNumberLabel              2020	//(Left Origin = 81, Top Origin = 110, Usable = 1, Font = Standard)
#define DebugDataPalmIDLabel                      2021	//(Left Origin = 5, Top Origin = 81, Usable = 1, Font = Bold)
#define DebugDataPalmIDNumberLabel                2022	//(Left Origin = 81, Top Origin = 81, Usable = 1, Font = Standard)
#define DebugDataLoginStatusLabel                 2023	//(Left Origin = 106, Top Origin = 72, Usable = 1, Font = Standard)
#define DebugDataDrinkSyncLabel                   2024	//(Left Origin = 5, Top Origin = 130, Usable = 1, Font = Bold)
#define DebugDataDrinkSyncNumberLabel             2025	//(Left Origin = 81, Top Origin = 130, Usable = 1, Font = Standard)
#define DebugDataNumSeatRecordsLabel              2026	//(Left Origin = 134, Top Origin = 15, Usable = 1, Font = Standard)
#define DebugDataSeatsDBLabel                     2027	//(Left Origin = 85, Top Origin = 15, Usable = 1, Font = Bold)
#define DebugDataNumSeatsLabel                    2028	//(Left Origin = 51, Top Origin = 47, Usable = 1, Font = Standard)
#define DebugDataTotalSeatsLabel                  2029	//(Left Origin = 9, Top Origin = 47, Usable = 1, Font = Standard)
#define DebugDataNumTablesLabel                   2030	//(Left Origin = 51, Top Origin = 37, Usable = 1, Font = Standard)
#define DebugDataTotalTablesLabel                 2031	//(Left Origin = 9, Top Origin = 37, Usable = 1, Font = Standard)
#define DebugDataNumOrdersLabel                   2032	//(Left Origin = 51, Top Origin = 27, Usable = 1, Font = Standard)
#define DebugDataLogOffSecsLabel                  2033	//(Left Origin = 126, Top Origin = 90, Usable = 1, Font = Standard)
#define DebugDataBtTxLabel                        2035	//(Left Origin = 5, Top Origin = 140, Usable = 1, Font = Bold)
#define DebugDataBtTxTicksLabel                   2036	//(Left Origin = 31, Top Origin = 140, Usable = 1, Font = Standard)
#define DebugDataBtRxLabel                        2037	//(Left Origin = 59, Top Origin = 140, Usable = 1, Font = Bold)
#define DebugDataBtRxTicksLabel                   2038	//(Left Origin = 88, Top Origin = 140, Usable = 1, Font = Standard)

//	Resource: tFRM 2100
#define KeypadForm                                2100	//(Left Origin = 2, Top Origin = 20, Width = 156, Height = 138, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define KeypadOkayButton                          2101	//(Left Origin = 7, Top Origin = 122, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define KeypadZeroButton                          2102	//(Left Origin = 59, Top Origin = 103, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define KeypadZeroZeroButton                      2103	//(Left Origin = 91, Top Origin = 103, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define KeypadAmountButton                        2105	//(Left Origin = 9, Top Origin = 18, Width = 138, Height = 17, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define KeypadSevenButton                         2106	//(Left Origin = 58, Top Origin = 43, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define KeypadFourButton                          2107	//(Left Origin = 58, Top Origin = 63, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define KeypadOneButton                           2108	//(Left Origin = 58, Top Origin = 83, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define KeypadEightButton                         2109	//(Left Origin = 90, Top Origin = 43, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define KeypadFiveButton                          2110	//(Left Origin = 90, Top Origin = 63, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define KeypadTwoButton                           2111	//(Left Origin = 90, Top Origin = 83, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define KeypadNineButton                          2112	//(Left Origin = 122, Top Origin = 43, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define KeypadSixButton                           2113	//(Left Origin = 122, Top Origin = 63, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define KeypadThreeButton                         2114	//(Left Origin = 122, Top Origin = 83, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define KeypadClearButton                         2115	//(Left Origin = 122, Top Origin = 103, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define KeypadCancelButton                        2116	//(Left Origin = 59, Top Origin = 122, Width = 88, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)

//	Resource: tFRM 2300
#define EnterPINForm                              2300	//(Left Origin = 2, Top Origin = 18, Width = 156, Height = 140, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 2311)
#define EnterPINOkayButton                        2301	//(Left Origin = 8, Top Origin = 120, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define EnterPINLogOffButton                      2302	//(Left Origin = 56, Top Origin = 120, Width = 44, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define EnterPINClearButton                       2303	//(Left Origin = 108, Top Origin = 120, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define EnterPINDisplayButton                     2304	//(Left Origin = 32, Top Origin = 20, Width = 92, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define EnterPIN0Button                           2310	//(Left Origin = 66, Top Origin = 96, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define EnterPIN1Button                           2311	//(Left Origin = 33, Top Origin = 42, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define EnterPIN2Button                           2312	//(Left Origin = 65, Top Origin = 42, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define EnterPIN3Button                           2313	//(Left Origin = 98, Top Origin = 42, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define EnterPIN4Button                           2314	//(Left Origin = 32, Top Origin = 60, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define EnterPIN5Button                           2315	//(Left Origin = 65, Top Origin = 60, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define EnterPIN6Button                           2316	//(Left Origin = 98, Top Origin = 60, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define EnterPIN7Button                           2317	//(Left Origin = 32, Top Origin = 78, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define EnterPIN8Button                           2318	//(Left Origin = 65, Top Origin = 78, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define EnterPIN9Button                           2319	//(Left Origin = 98, Top Origin = 78, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)

//	Resource: tFRM 2200
#define OverviewForm                              2200	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 1, Help ID = 0, Menu Bar ID = 2200, Default Button ID = 0)
#define OverviewSelectViewButton                  2204	//(Left Origin = 68, Top Origin = 0, Width = 16, Height = 16, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define OverviewSelectAllButton                   2212	//(Left Origin = 144, Top Origin = 17, Width = 16, Height = 16, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define OverviewSelectButton                      2214	//(Left Origin = 117, Top Origin = 1, Width = 41, Height = 10, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define OverviewDeselectAllButton                 2217	//(Left Origin = 144, Top Origin = 37, Width = 16, Height = 16, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define OverviewHappyHourButton                   2218	//(Left Origin = 86, Top Origin = 0, Width = 9, Height = 12, Usable = 0, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Bold)
#define OverviewPaidButton                        2220	//(Left Origin = 142, Top Origin = 62, Width = 18, Height = 18, Usable = 0, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define OverviewSelectAllBitMap                   10	//(Left Origin = 144, Top Origin = 17, Bitmap Resource ID = 10, Usable = 0)
#define OverviewDeselectAllBitMap                 12	//(Left Origin = 144, Top Origin = 37, Bitmap Resource ID = 12, Usable = 0)
#define OverviewUnderlineBitMap                   14	//(Left Origin = 70, Top Origin = 0, Bitmap Resource ID = 14, Usable = 0)
#define OverviewToggleviewBitMap                  15	//(Left Origin = 70, Top Origin = 0, Bitmap Resource ID = 15, Usable = 1)
#define OverviewPaidBitMap                        16	//(Left Origin = 144, Top Origin = 72, Bitmap Resource ID = 16, Usable = 0)
#define OverviewUnsentBitMap                      8	//(Left Origin = 144, Top Origin = 92, Bitmap Resource ID = 8, Usable = 0)
#define OverviewDishesList                        2216	//(Left Origin = 8, Top Origin = 8, Width = 140, Usable = 0, Font = Standard, Visible Items = 3)
#define OverviewStaffPopTrigger                   2202	//(Left Origin = 117, Top Origin = 0, Width = 43, Height = 13, Usable = 1, Anchor Left = 1, Font = Bold, List ID = 0)
#define OverviewScrollUpRepeating                 2203	//(Left Origin = 144, Top Origin = 131, Width = 16, Height = 14, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol 7)
#define OverviewScrollDownRepeating               2205	//(Left Origin = 144, Top Origin = 144, Width = 16, Height = 14, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol 7)
#define OverviewOverviewTable                     2201	//(Left Origin = 0, Top Origin = 15, Width = 160, Height = 145, Editable = 0, Rows = 14)

//	Resource: tFRM 2400
#define EditLineKeyboardForm                      2400	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define EditLineKeyboardOkayButton                2401	//(Left Origin = 10, Top Origin = 142, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define EditLineKeyboardCancelButton              2402	//(Left Origin = 60, Top Origin = 142, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define EditLineKeyboardNoteField                 2403	//(Left Origin = 10, Top Origin = 19, Width = 140, Height = 15, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Bold, Auto Shift = 1, Has Scroll Bar = 1, Numeric = 0)
#define EditLineKeyboardEnterNoteLabel            2404	//(Left Origin = 10, Top Origin = 20, Usable = 0, Font = Standard)
#define EditLineKeyboardAPushButton               2441	//(Left Origin = 9, Top Origin = 44, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardBPushButton               2442	//(Left Origin = 32, Top Origin = 44, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardCPushButton               2443	//(Left Origin = 55, Top Origin = 44, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardDPushButton               2444	//(Left Origin = 78, Top Origin = 44, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardEPushButton               2445	//(Left Origin = 101, Top Origin = 44, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardFPushButton               2446	//(Left Origin = 124, Top Origin = 44, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardGPushButton               2447	//(Left Origin = 9, Top Origin = 57, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardHPushButton               2448	//(Left Origin = 32, Top Origin = 57, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardIPushButton               2449	//(Left Origin = 55, Top Origin = 57, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardJPushButton               2450	//(Left Origin = 78, Top Origin = 57, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardKPushButton               2451	//(Left Origin = 101, Top Origin = 57, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardLPushButton               2452	//(Left Origin = 124, Top Origin = 57, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardMPushButton               2453	//(Left Origin = 9, Top Origin = 70, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardNPushButton               2454	//(Left Origin = 32, Top Origin = 70, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardOPushButton               2455	//(Left Origin = 55, Top Origin = 70, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardPPushButton               2456	//(Left Origin = 78, Top Origin = 70, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardQPushButton               2457	//(Left Origin = 101, Top Origin = 70, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardRPushButton               2458	//(Left Origin = 124, Top Origin = 70, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardSPushButton               2459	//(Left Origin = 9, Top Origin = 83, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardTPushButton               2460	//(Left Origin = 32, Top Origin = 83, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardUPushButton               2461	//(Left Origin = 55, Top Origin = 83, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardVPushButton               2462	//(Left Origin = 78, Top Origin = 83, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardWPushButton               2463	//(Left Origin = 101, Top Origin = 83, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardXPushButton               2464	//(Left Origin = 124, Top Origin = 83, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardYPushButton               2465	//(Left Origin = 9, Top Origin = 96, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardZPushButton               2466	//(Left Origin = 32, Top Origin = 96, Width = 22, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define EditLineKeyboardGroupID                   1

//	Resource: tFRM 2500
#define SystemInfoForm                            2500	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define SystemInfoOkayButton                      2501	//(Left Origin = 5, Top Origin = 140, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define SystemInfoDebugDataButton                 2520	//(Left Origin = 103, Top Origin = 5, Width = 4, Height = 4, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define SystemInfoOrdersLabel                     2502	//(Left Origin = 15, Top Origin = 72, Usable = 1, Font = Bold)
#define SystemInfoFreeOrdersLabel                 2503	//(Left Origin = 107, Top Origin = 94, Usable = 1, Font = Standard)
#define SystemInfoMenusLabel                      2504	//(Left Origin = 5, Top Origin = 27, Usable = 1, Font = Bold)
#define SystemInfoEqualsFreeOrdersLabel           2505	//(Left Origin = 101, Top Origin = 83, Usable = 1, Font = Bold)
#define SystemInfoUnSentLabel                     2506	//(Left Origin = 15, Top Origin = 83, Usable = 1, Font = Bold)
#define SystemInfoNumUnsentLabel                  2507	//(Left Origin = 60, Top Origin = 83, Usable = 1, Font = Standard)
#define SystemInfoFreeMemoryLabel                 2508	//(Left Origin = 84, Top Origin = 61, Usable = 1, Font = Bold)
#define SystemInfoMemoryLabel                     2509	//(Left Origin = 107, Top Origin = 72, Usable = 1, Font = Standard)
#define SystemInfoOrdersDBLabel                   2510	//(Left Origin = 5, Top Origin = 61, Usable = 1, Font = Bold)
#define SystemInfoDishesLabel                     2511	//(Left Origin = 16, Top Origin = 38, Usable = 1, Font = Bold)
#define SystemInfoDishesMenuLabel                 2512	//(Left Origin = 57, Top Origin = 38, Usable = 1, Font = Bold)
#define SystemInfoPalmNameLabel                   2513	//(Left Origin = 57, Top Origin = 15, Usable = 1, Font = Bold)
#define SystemInfoNameLabel                       2514	//(Left Origin = 4, Top Origin = 15, Usable = 1, Font = Bold)
#define SystemInfoBluetoothNameLabel              2515	//(Left Origin = 5, Top Origin = 119, Usable = 1, Font = Bold)
#define SystemInfoBtNameLabel                     2516	//(Left Origin = 62, Top Origin = 119, Usable = 1, Font = Standard)
#define SystemInfoBtAddressLabel                  2517	//(Left Origin = 63, Top Origin = 131, Usable = 1, Font = Standard)
#define SystemInfoBtPalmAddressLabel              2518	//(Left Origin = 63, Top Origin = 143, Usable = 1, Font = Standard)
#define SystemInfoPalmLabel                       2519	//(Left Origin = 41, Top Origin = 143, Usable = 1, Font = Standard)
#define SystemInfoDrinksLabel                     2521	//(Left Origin = 16, Top Origin = 48, Usable = 1, Font = Bold)
#define SystemInfoDrinksMenuLabel                 2522	//(Left Origin = 57, Top Origin = 48, Usable = 1, Font = Bold)
#define SystemInfoNumSeatsLabel                   2528	//(Left Origin = 60, Top Origin = 104, Usable = 1, Font = Standard)
#define SystemInfoTotalSeatsLabel                 2529	//(Left Origin = 16, Top Origin = 104, Usable = 1, Font = Bold)
#define SystemInfoNumTablesLabel                  2530	//(Left Origin = 60, Top Origin = 94, Usable = 1, Font = Standard)
#define SystemInfoTotalTablesLabel                2531	//(Left Origin = 15, Top Origin = 94, Usable = 1, Font = Bold)
#define SystemInfoNumOrdersLabel                  2532	//(Left Origin = 60, Top Origin = 72, Usable = 1, Font = Standard)

//	Resource: tFRM 1700
#define CallAwayForm                              1700	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define CallAwayBeamButton                        1701	//(Left Origin = 57, Top Origin = 139, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define CallAwayCancelButton                      1703	//(Left Origin = 8, Top Origin = 139, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define CallAwayChoicesList                       1702	//(Left Origin = 18, Top Origin = 22, Width = 120, Usable = 1, Font = Standard, Visible Items = 1)

//	Resource: tFRM 2600
#define NumberEntryFieldForm                      2600	//(Left Origin = 2, Top Origin = 98, Width = 156, Height = 60, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define NumberEntryFieldOkayButton                2602	//(Left Origin = 10, Top Origin = 44, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define NumberEntryFieldNumberEntryField          2601	//(Left Origin = 28, Top Origin = 24, Width = 99, Height = 14, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 10, Font = Large, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)

//	Resource: tFRM 1200
#define RegisterForm                              1200	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1, Menu Bar ID = 0, Default Button ID = 0)
#define RegisterOkayButton                        1202	//(Left Origin = 10, Top Origin = 137, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define RegisterPINButton                         1207	//(Left Origin = 110, Top Origin = 137, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define RegisterCancelButton                      1210	//(Left Origin = 60, Top Origin = 137, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define RegisterReplaceCheckbox                   1203	//(Left Origin = 7, Top Origin = 26, Width = 140, Height = 19, Usable = 1, Selected = 0, Group ID = 0, Font = Bold)
#define RegisterSyncPrintCheckbox                 1208	//(Left Origin = 7, Top Origin = 91, Width = 105, Height = 19, Usable = 0, Selected = 0, Group ID = 0, Font = Bold)
#define RegisterNewNameField                      1204	//(Left Origin = 8, Top Origin = 65, Width = 141, Height = 20, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 25, Font = Bold, Auto Shift = 1, Has Scroll Bar = 0, Numeric = 0)
#define RegisterNewNameLabel                      1205	//(Left Origin = 10, Top Origin = 51, Usable = 1, Font = Bold)
#define RegisterSyncPrintLabel                    1206	//(Left Origin = 25, Top Origin = 111, Usable = 1, Font = Bold)
#define RegisterRegisteredPalmsList               1201	//(Left Origin = 8, Top Origin = 16, Width = 137, Usable = 0, Font = Standard, Visible Items = 20)

//	Resource: tFRM 1800
#define ScreenLockForm                            1800	//(Left Origin = 2, Top Origin = 141, Width = 156, Height = 17, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ScreenLock1Button                         1805	//(Left Origin = 5, Top Origin = 2, Width = 19, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define ScreenLock2Button                         1806	//(Left Origin = 132, Top Origin = 2, Width = 19, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define ScreenLockPress1then2Label                1804	//(Left Origin = 32, Top Origin = 3, Usable = 1, Font = Bold)

//	Resource: tFRM 2700
#define UserSettingsForm                          2700	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define UserSettingsOkayButton                    2713	//(Left Origin = 8, Top Origin = 141, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define UserSettingsUserLevelLabel                2701	//(Left Origin = 19, Top Origin = 20, Usable = 1, Font = Bold)
#define UserSettingsTablesToGetLabel              2702	//(Left Origin = 1, Top Origin = 37, Usable = 1, Font = Bold)
#define UserSettingsFontSizeLabel                 2703	//(Left Origin = 26, Top Origin = 54, Usable = 1, Font = Bold)
#define UserSettingsAutoDetailsLabel              2704	//(Left Origin = 8, Top Origin = 71, Usable = 1, Font = Bold)
#define UserSettingsSoundLevelLabel               2710	//(Left Origin = 12, Top Origin = 87, Usable = 1, Font = Bold)
#define UserSettingsScreenLockLabel               2712	//(Left Origin = 11, Top Origin = 104, Usable = 1, Font = Bold)
#define UserSettingsDisplayStyleLabel             2714	//(Left Origin = 6, Top Origin = 121, Usable = 1, Font = Bold)
#define UserSettingsChoicesList                   2716	//(Left Origin = 18, Top Origin = 22, Width = 120, Usable = 0, Font = Standard, Visible Items = 1)
#define UserSettingsTablesToGetPopTrigger         2705	//(Left Origin = 76, Top Origin = 37, Width = 78, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 0)
#define UserSettingsFontSizePopTrigger            2706	//(Left Origin = 76, Top Origin = 54, Width = 78, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 0)
#define UserSettingsAutoDetailsPopTrigger         2707	//(Left Origin = 76, Top Origin = 71, Width = 78, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 0)
#define UserSettingsSoundLevelPopTrigger          2708	//(Left Origin = 76, Top Origin = 87, Width = 78, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 0)
#define UserSettingsScreenLockPopTrigger          2709	//(Left Origin = 76, Top Origin = 104, Width = 78, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 0)
#define UserSettingsDisplayStylePopTrigger        2711	//(Left Origin = 76, Top Origin = 121, Width = 78, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 0)
#define UserSettingsUserLevelPopTrigger           2715	//(Left Origin = 76, Top Origin = 20, Width = 78, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 0)

//	Resource: tFRM 2800
#define CopyTimesForm                             2800	//(Left Origin = 2, Top Origin = 33, Width = 156, Height = 125, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define CopyTimesOkayButton                       2801	//(Left Origin = 7, Top Origin = 108, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define CopyTimesZeroButton                       2802	//(Left Origin = 59, Top Origin = 91, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define CopyTimesZeroZeroButton                   2803	//(Left Origin = 91, Top Origin = 91, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define CopyTimesSevenButton                      2806	//(Left Origin = 58, Top Origin = 31, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define CopyTimesFourButton                       2807	//(Left Origin = 58, Top Origin = 51, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define CopyTimesOneButton                        2808	//(Left Origin = 58, Top Origin = 71, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define CopyTimesEightButton                      2809	//(Left Origin = 90, Top Origin = 31, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define CopyTimesFiveButton                       2810	//(Left Origin = 90, Top Origin = 51, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define CopyTimesTwoButton                        2811	//(Left Origin = 90, Top Origin = 71, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define CopyTimesNineButton                       2812	//(Left Origin = 122, Top Origin = 31, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define CopyTimesSixButton                        2813	//(Left Origin = 122, Top Origin = 51, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define CopyTimesThreeButton                      2814	//(Left Origin = 122, Top Origin = 71, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define CopyTimesClearButton                      2815	//(Left Origin = 122, Top Origin = 91, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define CopyTimesStandardPriceButton              2816	//(Left Origin = 59, Top Origin = 108, Width = 88, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define CopyTimesAmountLabel                      2804	//(Left Origin = 53, Top Origin = 15, Usable = 1, Font = Bold)


//	Resource: Talt 1210
#define ConfDeleteAllSentAlert                    1210
#define ConfDeleteAllSentOK                       0
#define ConfDeleteAllSentCancel                   1

//	Resource: Talt 1260
#define ConfSyncWillDeleteAlert                   1260
#define ConfSyncWillDeleteOK                      0
#define ConfSyncWillDeleteCancel                  1

//	Resource: Talt 1310
#define WarnTxdRxdOrdersDontEquateAlert           1310
#define WarnTxdRxdOrdersDontEquateOK              0

//	Resource: Talt 1200
#define ConfDeleteDBAlert                         1200
#define ConfDeleteDBOK                            0
#define ConfDeleteDBCancel                        1

//	Resource: Talt 1220
#define ConfDeleteTableAlert                      1220
#define ConfDeleteTableOK                         0
#define ConfDeleteTableCancel                     1

//	Resource: Talt 1230
#define ConfDeleteSeatAlert                       1230
#define ConfDeleteSeatOK                          0
#define ConfDeleteSeatCancel                      1

//	Resource: Talt 1120
#define ErrDatabaseSyncFailureAlert               1120
#define ErrDatabaseSyncFailureOK                  0

//	Resource: Talt 1240
#define ConfDeleteUnbilledAlert                   1240
#define ConfDeleteUnbilledOK                      0
#define ConfDeleteUnbilledCancel                  1

//	Resource: Talt 1000
#define ErrRomIncompatibleAlert                   1000
#define ErrRomIncompatibleOK                      0

//	Resource: Talt 1250
#define ConfDeleteUnbilledSeatAlert               1250
#define ConfDeleteUnbilledSeatOK                  0
#define ConfDeleteUnbilledSeatCancel              1

//	Resource: Talt 1130
#define WarnBeamWillDestroyDishesDBAlert          1130
#define WarnBeamWillDestroyDishesDBOK             0

//	Resource: Talt 1300
#define InfMoveTableAlert                         1300
#define InfMoveTableOK                            0

//	Resource: Talt 1280
#define ConfDeleteThisDishAlert                   1280
#define ConfDeleteThisDishOK                      0
#define ConfDeleteThisDishCancel                  1

//	Resource: Talt 1400
#define WarnSeatBilledNotBeamedAlert              1400
#define WarnSeatBilledNotBeamedOK                 0

//	Resource: Talt 1100
#define WarnDishesDBNotSyncAlert                  1100
#define WarnDishesDBNotSyncOK                     0

//	Resource: Talt 1140
#define InfBeamingFailureAlert                    1140
#define InfBeamingFailureOK                       0

//	Resource: Talt 1010
#define InfPrintingRedirectedAlert                1010
#define InfPrintingRedirectedOK                   0

//	Resource: Talt 1020
#define InfNoDishesMenuFoundAlert                 1020
#define InfNoDishesMenuFoundOK                    0

//	Resource: Talt 1110
#define WarnPalmNotRegisteredAlert                1110
#define WarnPalmNotRegisteredOK                   0

//	Resource: Talt 1150
#define WarnCantAlterSentOrderAlert               1150
#define WarnCantAlterSentOrderOK                  0

//	Resource: Talt 1290
#define ConfCreditThisDishAlert                   1290
#define ConfCreditThisDishOK                      0
#define ConfCreditThisDishCancel                  1

//	Resource: Talt 1105
#define WarnServerDatabaseErrorAlert              1105
#define WarnServerDatabaseErrorOK                 0

//	Resource: Talt 1500
#define InfLoginBeamNowAlert                      1500
#define InfLoginBeamNowOK                         0

//	Resource: Talt 1510
#define WarnLoginBeamForUsersListAlert            1510
#define WarnLoginBeamForUsersListOK               0

//	Resource: Talt 1520
#define WarnLoginNotLoggedInAlert                 1520
#define WarnLoginNotLoggedInOK                    0

//	Resource: Talt 1530
#define WarnLoginWrongPINAlert                    1530
#define WarnLoginWrongPINOK                       0

//	Resource: Talt 1540
#define WarnLoginUserListChangedAlert             1540
#define WarnLoginUserListChangedOK                0

//	Resource: Talt 1550
#define WarnLoginTooManyPalmsAlert                1550
#define WarnLoginTooManyPalmsOK                   0

//	Resource: Talt 1560
#define WarnMustLogInFirstAlert                   1560
#define WarnMustLogInFirstOK                      0

//	Resource: Talt 1570
#define WarnPINMustBe10CharsAlert                 1570
#define WarnPINMustBe10CharsOK                    0

//	Resource: Talt 1160
#define WarnMenuDishDisabledAlert                 1160
#define WarnMenuDishDisabledOK                    0

//	Resource: Talt 1580
#define ConfDeleteUnsentOrdersAlert               1580
#define ConfDeleteUnsentOrdersBeam                0
#define ConfDeleteUnsentOrdersShowUnsentOrders    1

//	Resource: Talt 1030
#define InfPalmUniqueIDnotFoundAlert              1030
#define InfPalmUniqueIDnotFoundOK                 0

//	Resource: Talt 1040
#define InfNoPrinterFoundAlert                    1040
#define InfNoPrinterFoundOK                       0

//	Resource: Talt 1170
#define WarnCantDeleteLastSplitItemAlert          1170
#define WarnCantDeleteLastSplitItemOK             0

//	Resource: Talt 1590
#define WarnMaxBillingGroupsAlert                 1590
#define WarnMaxBillingGroupsOK                    0

//	Resource: Talt 1591
#define WarnMaxSplittingGroupsAlert               1591
#define WarnMaxSplittingGroupsOK                  0

//	Resource: Talt 1050
#define InfMessageReceivedAlert                   1050
#define InfMessageReceivedOK                      0

//	Resource: Talt 1190
#define WarnMaxDrinkMixItemsAlert                 1190
#define WarnMaxDrinkMixItemsOK                    0

//	Resource: Talt 1145
#define InfBeamingTooLargeAlert                   1145
#define InfBeamingTooLargeOK                      0

//	Resource: Talt 1101
#define WarnDrinksDBNotSyncAlert                  1101
#define WarnDrinksDBNotSyncOK                     0

//	Resource: Talt 1131
#define WarnBeamWillDestroyDrinksDBAlert          1131
#define WarnBeamWillDestroyDrinksDBOK             0

//	Resource: Talt 1012
#define InfPrinterOfflineAlert                    1012
#define InfPrinterOfflineOK                       0

//	Resource: Talt 1447
#define WarnUserCancelledAlert                    1447
#define WarnUserCancelledOK                       0

//	Resource: Talt 1281
#define ConfDeleteSetMenuMasterAlert              1281
#define ConfDeleteSetMenuMasterOK                 0
#define ConfDeleteSetMenuMasterCancel             1

//	Resource: Talt 1151
#define WarnCantPriceAdjustSetMenuAlert           1151
#define WarnCantPriceAdjustSetMenuOK              0

//	Resource: Talt 1152
#define WarnNoPriceAdjustRightsAlert              1152
#define WarnNoPriceAdjustRightsOK                 0

//	Resource: Talt 1135
#define WarnMaxDisplayItemsAlert                  1135
#define WarnMaxDisplayItemsOK                     0

//	Resource: Talt 1251
#define InfGlassIndexLostAlert                    1251
#define InfGlassIndexLostOK                       0

//	Resource: Talt 1592
#define WarnMaxSetMenuGroupsAlert                 1592
#define WarnMaxSetMenuGroupsOK                    0

//	Resource: Talt 1112
#define WarnWillNowRegisterPalmAlert              1112
#define WarnWillNowRegisterPalmOK                 0
#define WarnWillNowRegisterPalmCancel             1

//	Resource: Talt 1205
#define ConfDeleteDBAndSettingsAlert              1205
#define ConfDeleteDBAndSettingsOK                 0
#define ConfDeleteDBAndSettingsCancel             1

//	Resource: Talt 1581
#define ConfDeleteOldUnsentOrdersAlert            1581
#define ConfDeleteOldUnsentOrdersBeam             0
#define ConfDeleteOldUnsentOrdersShowUnsentOrders 1

//	Resource: Talt 1600
#define InfMessageAlert                           1600
#define InfMessageOK                              0

//	Resource: Talt 1114
#define WarnBluetoothDiscoveryAlert               1114
#define WarnBluetoothDiscoveryOK                  0
#define WarnBluetoothDiscoveryCancel              1

//	Resource: Talt 1142
#define InfBeamFailSelectNewAlert                 1142
#define InfBeamFailSelectNewTryAgain              0
#define InfBeamFailSelectNewSelectNew             1

//	Resource: Talt 1180
#define ConfCancelForcedSideOrOptAlert            1180
#define ConfCancelForcedSideOrOptKEEP             0
#define ConfCancelForcedSideOrOptTRASHORDER       1

//	Resource: Talt 1511
#define WarnLoginBeamForPalmsListAlert            1511
#define WarnLoginBeamForPalmsListOK               0

//	Resource: Talt 1153
#define WarnSideCantBeSetMenuMasterAlert          1153
#define WarnSideCantBeSetMenuMasterOK             0

//	Resource: Talt 1005
#define WarnVersionUpdateAlert                    1005
#define WarnVersionUpdateCancel                   0
#define WarnVersionUpdateProceed                  1

//	Resource: Talt 1583
#define ConfDontBeamUnsentOrdersAlert             1583
#define ConfDontBeamUnsentOrdersBeamNow           0
#define ConfDontBeamUnsentOrdersTakemoreorders    1

//	Resource: Talt 1021
#define InfNoDrinksMenuFoundAlert                 1021
#define InfNoDrinksMenuFoundOK                    0

//	Resource: Talt 1282
#define ConfDeleteAllUnsentAlert                  1282
#define ConfDeleteAllUnsentOK                     0
#define ConfDeleteAllUnsentCancel                 1

//	Resource: Talt 1295
#define ConfFlattenBatteryAlert                   1295
#define ConfFlattenBatteryOK                      0
#define ConfFlattenBatteryCancel                  1

//	Resource: Talt 1320
#define ConfDeleteSideOrOptionAlert               1320
#define ConfDeleteSideOrOptionDelete              0
#define ConfDeleteSideOrOptionCancel              1

//	Resource: Talt 1014
#define InfCallAwayPrinterNotSetUpAlert           1014
#define InfCallAwayPrinterNotSetUpOK              0

//	Resource: Talt 1016
#define InfKitchenPrinterNotSetUpAlert            1016
#define InfKitchenPrinterNotSetUpOK               0


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MBAR 1200
#define EditFormMenuBar                           1200

//	Resource: MBAR 2200
#define OverviewFormMenuBar                       2200

//	Resource: MBAR 1100
#define DisplayDataFormMenuBar                    1100

//	Resource: MBAR 1600
#define TableFormMenuBar                          1600


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsBluetoothDevice                1000	//  Command Key: B
#define MainOptionsUserSettings                   1002	//  Command Key: U

//	Resource: MENU 1220
#define EditEditMenu                              1220
#define EditEditCut                               1220	//  Command Key: X
#define EditEditCopy                              1221	//  Command Key: C
#define EditEditPaste                             1222	//  Command Key: P
#define EditEditUndo                              1223	//  Command Key: U
#define EditEditSelectAll                         1224	//  Command Key: S
#define EditEditKeyboard                          1226	//  Command Key: K
#define EditEditGraffiti                          1227	//  Command Key: G

//	Resource: MENU 1210
#define EditOptionsMenu                           1210
#define EditOptionsGetInfo                        1210	//  Command Key: I
#define EditOptionsGototopofpage                  1211	//  Command Key: T
#define EditOptionsGotobottomofpage               1212	//  Command Key: B
#define EditOptionsMenuItem1213                   1213

//	Resource: MENU 1230
#define EditPageMenu                              1230
#define EditPageNewPage                           1230	//  Command Key: N
#define EditPageDeletePage                        1231	//  Command Key: D

//	Resource: MENU 1200
#define TestMenu                                  1200
#define TestLogDatabaseNow                        1200
#define TestEnableDatabaseLog                     1201
#define TestDisableDatabaseLog                    1202
#define TestClearHotSyncLog                       1204
#define TestEnableMessageLog                      1205
#define TestDisableMessageLog                     1206
#define TestMarkAllOrdersAsSent                   1208
#define TestUnsendAllOrders                       1209
#define TestLoadDummyMenu                         1211

//	Resource: MENU 1100
#define OverviewOptionsMenu                       1100
#define OverviewOptionsBluetoothDevice            1100	//  Command Key: B
#define OverviewOptionsUserSettings               1102	//  Command Key: U

//	Resource: MENU 1300
#define MainSetupMenu                             1300
#define MainSetupRegisterPalm                     1300
#define MainSetupDeleteDatabase                   1302
#define MainSetupDeleteDBAllSettings              1303
#define MainSetupFindAllBluetoothDevices          1305
#define MainSetupFindMoreBluetoothDevices         1306

//	Resource: MENU 1050
#define TableOptionsMenu                          1050
#define TableOptionsBluetoothDevice               1050	//  Command Key: B
#define TableOptionsUserSettings                  1052	//  Command Key: U

//	Resource: MENU 1500
#define MainAboutMenu                             1500
#define MainAboutSystemInfo                       1500
#define MainAboutAboutMenuMate                    1502

//	Resource: MENU 1600
#define BlueToothMenu                             1600
#define BlueToothSetFirstByteTOut                 1600
#define BlueToothSetInterByteTOut                 1601
#define BlueToothSetSendOrdersTOut                1602
#define BlueToothSetGetAllOrdersTOut              1603

//	Resource: MENU 1330
#define TableSetupMenu                            1330
#define TableSetupRegisterPalm                    1330
#define TableSetupDeleteDatabase                  1332
#define TableSetupDeleteDBAllSettings             1333
#define TableSetupFindAllBluetoothDevices         1335
#define TableSetupFindMoreBluetoothDevices        1336

//	Resource: MENU 1360
#define OverviewSetupMenu                         1360
#define OverviewSetupRegisterPalm                 1360
#define OverviewSetupDeleteDatabase               1362
#define OverviewSetupDeleteDBAllSettings          1363
#define OverviewSetupFindAllBluetoothDevices      1365
#define OverviewSetupFindMoreBluetoothDevices     1366

//	Resource: MENU 1530
#define TableAboutMenu                            1530
#define TableAboutSystemInfo                      1530
#define TableAboutAboutMenuMate                   1532

//	Resource: MENU 1560
#define OverviewAboutMenu                         1560
#define OverviewAboutSystemInfo                   1560
#define OverviewAboutAboutMenuMate                1562

//	Resource: MENU 1400
#define ForceMenu                                 1400
#define ForceFlattenBattery                       1400
#define ForceDeregisterPalm                       1402
#define ForceForceLogin                           1404
#define ForceNumberOfTables                       1406
#define ForceNumberOfSeats                        1407
#define ForceNumberOfOrdersPerSeat                1408
#define ForceNumberOfSeatNames                    1409
#define ForceGenerateFixedOrders                  1410
#define ForceGenerateRandomOrders                 1411


//	Resource: tSTR 100
#define FindHeaderTitleString                     100	// "Menus"

//	Resource: tSTR 1307
#define HelpIDString                              1307	// "Use 'Options' + or - pop lists to select a desired option for the current order.   To Delete a selected Option, just Tap it.  Tap 'Note' to attach a note to the current order.   Tap 'Delete' to delete this dish fro"

//	Resource: tSTR 1107
#define HelpInfoformString                        1107	// "MenuMate is a product of IQWorks Ltd. New Zealand.  For information and support contact us at:  Email:    support@iqworks.co.nz  Telephone:    +64 3 343 1202"

//	Resource: tSTR 1
#define RegistrationHelpString                    1	// "New Name: Enter the name for the new Palm. Filled in a"


//	Resource: tAIS 1000
#define CategoryLabelsAppInfoStr                  1000


//	Resource: PICT 1110
#define CompanyLogoBitmap                         1110

//	Resource: PICT 1
#define DrinksIconBitmap                          1

//	Resource: PICT 2
#define FoodIconBitmap                            2

//	Resource: PICT 15
#define ToggelviewBitmap                          15

//	Resource: PICT 4
#define HourGlassIconBitmap                       4

//	Resource: PICT 5
#define OverviewTableIconBitmap                   5

//	Resource: PICT 6
#define OverviewSeatsIconBitmap                   6

//	Resource: PICT 7
#define OverviewGroupsIconBitmap                  7

//	Resource: PICT 10
#define OverviewSelectAllBitmap                   10

//	Resource: PICT 11
#define OverviewGroupMarkedBitmap                 11

//	Resource: PICT 12
#define OverviewCancelAllBitmap                   12

//	Resource: PICT 13
#define OverviewSplitIconBitmap                   13

//	Resource: PICT 14
#define OverviewUnderlineBitmap                   14

//	Resource: PICT 16
#define OverviewPaidIconBitmap                    16

//	Resource: PICT 17
#define DownArrowBitmap                           17

//	Resource: PICT 18
#define CreatedforBitmapResourceIDBitmap          18

//	Resource: PICT 8
#define BitmapID8Bitmap                           8


//	Resource: tbmf 8
#define BitmapResourceID8BitmapFamily             8

//	Resource: tbmf 16
#define BitmapResourceID16BitmapFamily            16

//	Resource: tbmf 12
#define BitmapResourceID12BitmapFamily            12

//	Resource: tbmf 10
#define BitmapResourceID10BitmapFamily            10

//	Resource: tbmf 5
#define BitmapResourceID5BitmapFamily             5

//	Resource: tbmf 6
#define BitmapResourceID6BitmapFamily             6

//	Resource: tbmf 1
#define BitmapResourceID1BitmapFamily             1

//	Resource: tbmf 2
#define BitmapResourceID2BitmapFamily             2

//	Resource: tbmf 15
#define BitmapResourceID15BitmapFamily            15

