//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loyalty_mate_test_console.LoyaltyMateWCFServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_SalesforceAuthInfo", Namespace="http://schemas.datacontract.org/2004/07/MenumateServices.DTO.LoyaltyMate")]
    [System.SerializableAttribute()]
    public partial class DTO_SalesforceAuthInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_MMServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/MenumateServices.DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyMemberResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyMemberListResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyMemberActivationResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyResponse))]
    public partial class DTO_MMServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccesfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Succesful {
            get {
                return this.SuccesfulField;
            }
            set {
                if ((this.SuccesfulField.Equals(value) != true)) {
                    this.SuccesfulField = value;
                    this.RaisePropertyChanged("Succesful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_LoyaltyMemberResponse", Namespace="http://schemas.datacontract.org/2004/07/MenumateServices.DTO.LoyaltyMate")]
    [System.SerializableAttribute()]
    public partial class DTO_LoyaltyMemberResponse : Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_MMServiceResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_MemberInfo MemberInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.LoyaltyResponseCode ResponseCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_MemberInfo MemberInfo {
            get {
                return this.MemberInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberInfoField, value) != true)) {
                    this.MemberInfoField = value;
                    this.RaisePropertyChanged("MemberInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.LoyaltyResponseCode ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_LoyaltyMemberListResponse", Namespace="http://schemas.datacontract.org/2004/07/MenumateServices.DTO.LoyaltyMate")]
    [System.SerializableAttribute()]
    public partial class DTO_LoyaltyMemberListResponse : Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_MMServiceResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_MemberInfo> MemberListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.LoyaltyResponseCode ResponseCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_MemberInfo> MemberList {
            get {
                return this.MemberListField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberListField, value) != true)) {
                    this.MemberListField = value;
                    this.RaisePropertyChanged("MemberList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.LoyaltyResponseCode ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_LoyaltyMemberActivationResponse", Namespace="http://schemas.datacontract.org/2004/07/MenumateServices.DTO.LoyaltyMate")]
    [System.SerializableAttribute()]
    public partial class DTO_LoyaltyMemberActivationResponse : Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_MMServiceResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_MemberActivationInfo ActivationInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.LoyaltyResponseCode ResponseCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_MemberActivationInfo ActivationInfo {
            get {
                return this.ActivationInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivationInfoField, value) != true)) {
                    this.ActivationInfoField = value;
                    this.RaisePropertyChanged("ActivationInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.LoyaltyResponseCode ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_LoyaltyResponse", Namespace="http://schemas.datacontract.org/2004/07/MenumateServices.DTO.LoyaltyMate")]
    [System.SerializableAttribute()]
    public partial class DTO_LoyaltyResponse : Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_MMServiceResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.LoyaltyResponseCode ResponseCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.LoyaltyResponseCode ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoyaltyResponseCode", Namespace="http://schemas.datacontract.org/2004/07/MenumateServices.DTO.LoyaltyMate")]
    public enum LoyaltyResponseCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Successful = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SaveSalesforceAuthFailed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SalesforceAuthFailed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TrineoAuthFailed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreateMemberFailed = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateMemberFailed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberDoesNotExistInTheCloud = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteMemberFailed = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetMemberFailed = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberAlreadyExistsInTheCloud = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PostTransactionFailed = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetMemberByActivationCodeFailed = 11,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_MemberInfo", Namespace="http://schemas.datacontract.org/2004/07/MenumateServices.DTO.LoyaltyMate")]
    [System.SerializableAttribute()]
    public partial class DTO_MemberInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivationTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EarnedPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LoadedPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activated {
            get {
                return this.ActivatedField;
            }
            set {
                if ((this.ActivatedField.Equals(value) != true)) {
                    this.ActivatedField = value;
                    this.RaisePropertyChanged("Activated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivationToken {
            get {
                return this.ActivationTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivationTokenField, value) != true)) {
                    this.ActivationTokenField = value;
                    this.RaisePropertyChanged("ActivationToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellPhone {
            get {
                return this.CellPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CellPhoneField, value) != true)) {
                    this.CellPhoneField = value;
                    this.RaisePropertyChanged("CellPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMailAddress {
            get {
                return this.EMailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailAddressField, value) != true)) {
                    this.EMailAddressField = value;
                    this.RaisePropertyChanged("EMailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EarnedPoints {
            get {
                return this.EarnedPointsField;
            }
            set {
                if ((this.EarnedPointsField.Equals(value) != true)) {
                    this.EarnedPointsField = value;
                    this.RaisePropertyChanged("EarnedPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LoadedPoints {
            get {
                return this.LoadedPointsField;
            }
            set {
                if ((this.LoadedPointsField.Equals(value) != true)) {
                    this.LoadedPointsField = value;
                    this.RaisePropertyChanged("LoadedPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID {
            get {
                return this.UUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UUIDField, value) != true)) {
                    this.UUIDField = value;
                    this.RaisePropertyChanged("UUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_MemberActivationInfo", Namespace="http://schemas.datacontract.org/2004/07/MenumateServices.DTO.LoyaltyMate")]
    [System.SerializableAttribute()]
    public partial class DTO_MemberActivationInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExpiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivationCode {
            get {
                return this.ActivationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivationCodeField, value) != true)) {
                    this.ActivationCodeField = value;
                    this.RaisePropertyChanged("ActivationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Expired {
            get {
                return this.ExpiredField;
            }
            set {
                if ((this.ExpiredField.Equals(value) != true)) {
                    this.ExpiredField = value;
                    this.RaisePropertyChanged("Expired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID {
            get {
                return this.UUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UUIDField, value) != true)) {
                    this.UUIDField = value;
                    this.RaisePropertyChanged("UUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_TransactionInfo", Namespace="http://schemas.datacontract.org/2004/07/MenumateServices.DTO.LoyaltyMate")]
    [System.SerializableAttribute()]
    public partial class DTO_TransactionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EarnedPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EarnedPointsDeltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LoadedPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LoadedPointsDeltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OccurredAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EarnedPoints {
            get {
                return this.EarnedPointsField;
            }
            set {
                if ((this.EarnedPointsField.Equals(value) != true)) {
                    this.EarnedPointsField = value;
                    this.RaisePropertyChanged("EarnedPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EarnedPointsDelta {
            get {
                return this.EarnedPointsDeltaField;
            }
            set {
                if ((this.EarnedPointsDeltaField.Equals(value) != true)) {
                    this.EarnedPointsDeltaField = value;
                    this.RaisePropertyChanged("EarnedPointsDelta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LoadedPoints {
            get {
                return this.LoadedPointsField;
            }
            set {
                if ((this.LoadedPointsField.Equals(value) != true)) {
                    this.LoadedPointsField = value;
                    this.RaisePropertyChanged("LoadedPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LoadedPointsDelta {
            get {
                return this.LoadedPointsDeltaField;
            }
            set {
                if ((this.LoadedPointsDeltaField.Equals(value) != true)) {
                    this.LoadedPointsDeltaField = value;
                    this.RaisePropertyChanged("LoadedPointsDelta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OccurredAt {
            get {
                return this.OccurredAtField;
            }
            set {
                if ((this.OccurredAtField.Equals(value) != true)) {
                    this.OccurredAtField = value;
                    this.RaisePropertyChanged("OccurredAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID {
            get {
                return this.UUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UUIDField, value) != true)) {
                    this.UUIDField = value;
                    this.RaisePropertyChanged("UUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoyaltyMateWCFServiceRef.IWCFServiceLoyaltyMate")]
    public interface IWCFServiceLoyaltyMate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceLoyaltyMate/SetSalesforceAuthInfo", ReplyAction="http://tempuri.org/IWCFServiceLoyaltyMate/SetSalesforceAuthInfoResponse")]
        Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyResponse SetSalesforceAuthInfo(Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_SalesforceAuthInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceLoyaltyMate/CreateMember", ReplyAction="http://tempuri.org/IWCFServiceLoyaltyMate/CreateMemberResponse")]
        Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyMemberResponse CreateMember(string inSyndicateCode, int inSiteID, Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_MemberInfo inInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceLoyaltyMate/UpdateMember", ReplyAction="http://tempuri.org/IWCFServiceLoyaltyMate/UpdateMemberResponse")]
        Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyMemberResponse UpdateMember(string inSyndicateCode, int inSiteID, Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_MemberInfo inInfo, bool inForceCreate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceLoyaltyMate/DeleteMember", ReplyAction="http://tempuri.org/IWCFServiceLoyaltyMate/DeleteMemberResponse")]
        Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyResponse DeleteMember(string inSyndicateCode, int inSiteID, string inUUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceLoyaltyMate/GetMember", ReplyAction="http://tempuri.org/IWCFServiceLoyaltyMate/GetMemberResponse")]
        Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyMemberResponse GetMember(string inSyndicateCode, int inSiteID, string inUUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceLoyaltyMate/GetMemberList", ReplyAction="http://tempuri.org/IWCFServiceLoyaltyMate/GetMemberListResponse")]
        Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyMemberListResponse GetMemberList(string inSyndicateCode, int inSiteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceLoyaltyMate/PostTransaction", ReplyAction="http://tempuri.org/IWCFServiceLoyaltyMate/PostTransactionResponse")]
        Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyResponse PostTransaction(string inSyndicateCode, int inSiteID, Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_TransactionInfo transaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceLoyaltyMate/GetMemberIdByActivationCode", ReplyAction="http://tempuri.org/IWCFServiceLoyaltyMate/GetMemberIdByActivationCodeResponse")]
        Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyMemberActivationResponse GetMemberIdByActivationCode(string inSyndicateCode, int inSideID, Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_MemberActivationInfo activationInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFServiceLoyaltyMateChannel : Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.IWCFServiceLoyaltyMate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFServiceLoyaltyMateClient : System.ServiceModel.ClientBase<Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.IWCFServiceLoyaltyMate>, Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.IWCFServiceLoyaltyMate {
        
        public WCFServiceLoyaltyMateClient() {
        }
        
        public WCFServiceLoyaltyMateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFServiceLoyaltyMateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceLoyaltyMateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceLoyaltyMateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyResponse SetSalesforceAuthInfo(Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_SalesforceAuthInfo info) {
            return base.Channel.SetSalesforceAuthInfo(info);
        }
        
        public Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyMemberResponse CreateMember(string inSyndicateCode, int inSiteID, Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_MemberInfo inInfo) {
            return base.Channel.CreateMember(inSyndicateCode, inSiteID, inInfo);
        }
        
        public Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyMemberResponse UpdateMember(string inSyndicateCode, int inSiteID, Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_MemberInfo inInfo, bool inForceCreate) {
            return base.Channel.UpdateMember(inSyndicateCode, inSiteID, inInfo, inForceCreate);
        }
        
        public Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyResponse DeleteMember(string inSyndicateCode, int inSiteID, string inUUID) {
            return base.Channel.DeleteMember(inSyndicateCode, inSiteID, inUUID);
        }
        
        public Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyMemberResponse GetMember(string inSyndicateCode, int inSiteID, string inUUID) {
            return base.Channel.GetMember(inSyndicateCode, inSiteID, inUUID);
        }
        
        public Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyMemberListResponse GetMemberList(string inSyndicateCode, int inSiteID) {
            return base.Channel.GetMemberList(inSyndicateCode, inSiteID);
        }
        
        public Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyResponse PostTransaction(string inSyndicateCode, int inSiteID, Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_TransactionInfo transaction) {
            return base.Channel.PostTransaction(inSyndicateCode, inSiteID, transaction);
        }
        
        public Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_LoyaltyMemberActivationResponse GetMemberIdByActivationCode(string inSyndicateCode, int inSideID, Loyalty_mate_test_console.LoyaltyMateWCFServiceRef.DTO_MemberActivationInfo activationInfo) {
            return base.Channel.GetMemberIdByActivationCode(inSyndicateCode, inSideID, activationInfo);
        }
    }
}
