object LoadBillScenarioFileForm: TLoadBillScenarioFileForm
  Left = 0
  Top = 0
  Caption = 'Load Bill scenario file'
  ClientHeight = 615
  ClientWidth = 996
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object pnLeft: TPanel
    Left = 0
    Top = 5
    Width = 5
    Height = 554
    Align = alLeft
    BevelOuter = bvNone
    TabOrder = 0
    ExplicitTop = -402
    ExplicitHeight = 703
  end
  object pnRight: TPanel
    Left = 991
    Top = 5
    Width = 5
    Height = 554
    Align = alRight
    BevelOuter = bvNone
    TabOrder = 1
    ExplicitLeft = 8
    ExplicitTop = 0
    ExplicitHeight = 301
  end
  object sbFileURI: TStatusBar
    Left = 0
    Top = 596
    Width = 996
    Height = 19
    Panels = <>
    ExplicitLeft = -8
    ExplicitTop = 283
    ExplicitWidth = 643
  end
  object pnTop: TPanel
    Left = 0
    Top = 0
    Width = 996
    Height = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 3
    ExplicitLeft = 5
    ExplicitWidth = 282
  end
  object pnBottom: TPanel
    Left = 0
    Top = 559
    Width = 996
    Height = 37
    Align = alBottom
    BevelOuter = bvNone
    TabOrder = 4
    ExplicitTop = 565
    object btnOK: TButton
      Left = 910
      Top = 6
      Width = 75
      Height = 25
      Caption = 'Accept'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clTeal
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ModalResult = 1
      ParentFont = False
      TabOrder = 0
    end
    object Button2: TButton
      Left = 816
      Top = 6
      Width = 75
      Height = 25
      Caption = 'Cancel'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clRed
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ModalResult = 2
      ParentFont = False
      TabOrder = 1
    end
  end
  object pnCenter: TPanel
    Left = 5
    Top = 5
    Width = 986
    Height = 554
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 5
    ExplicitLeft = 40
    ExplicitTop = 0
    ExplicitWidth = 889
    ExplicitHeight = 537
    object Splitter1: TSplitter
      Left = 396
      Top = 0
      Height = 554
      ExplicitLeft = 824
      ExplicitTop = 352
      ExplicitHeight = 100
    end
    object pnScenarioNames: TPanel
      Left = 0
      Top = 0
      Width = 396
      Height = 554
      Align = alLeft
      BevelOuter = bvNone
      TabOrder = 0
      ExplicitLeft = -211
      ExplicitTop = 1
      ExplicitHeight = 583
      object gbScenarios: TGroupBox
        Left = 0
        Top = 0
        Width = 396
        Height = 554
        Align = alClient
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 0
        ExplicitWidth = 345
        ExplicitHeight = 585
        object pnInputPriceHeader: TPanel
          Left = 2
          Top = 15
          Width = 392
          Height = 17
          Align = alTop
          BevelOuter = bvNone
          Caption = 'Scenarios'
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          ExplicitWidth = 341
        end
        object lvScenarios: TListView
          Left = 2
          Top = 32
          Width = 392
          Height = 520
          Align = alClient
          BorderStyle = bsNone
          Columns = <
            item
              Caption = 'Date'
              Width = 200
            end
            item
              AutoSize = True
              Caption = 'Name'
            end>
          ReadOnly = True
          RowSelect = True
          SortType = stText
          TabOrder = 1
          ViewStyle = vsReport
          OnDblClick = lvScenariosDblClick
          ExplicitWidth = 341
          ExplicitHeight = 549
        end
      end
    end
    object pnScenarioContent: TPanel
      Left = 399
      Top = 0
      Width = 587
      Height = 554
      Align = alClient
      BevelOuter = bvNone
      TabOrder = 1
      ExplicitLeft = 600
      ExplicitTop = 5
      ExplicitWidth = 391
      ExplicitHeight = 586
      object gbScenarioContent: TGroupBox
        Left = 0
        Top = 0
        Width = 587
        Height = 554
        Align = alClient
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 0
        ExplicitLeft = 216
        ExplicitWidth = 371
        ExplicitHeight = 586
        object lbSelectedScenarioName: TLabel
          Left = 2
          Top = 32
          Width = 583
          Height = 16
          Align = alTop
          Caption = 'Selected scenario'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clTeal
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentColor = False
          ParentFont = False
          ExplicitWidth = 115
        end
        object Panel1: TPanel
          Left = 2
          Top = 15
          Width = 583
          Height = 17
          Align = alTop
          BevelOuter = bvNone
          Caption = 'Content'
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          ExplicitWidth = 367
        end
        object reSelectedScenarioContent: TRichEdit
          Left = 2
          Top = 48
          Width = 583
          Height = 504
          Align = alClient
          BorderStyle = bsNone
          Font.Charset = ANSI_CHARSET
          Font.Color = clTeal
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          Lines.Strings = (
            'Selected scenario content')
          ParentFont = False
          TabOrder = 1
          ExplicitLeft = 320
          ExplicitTop = 168
          ExplicitWidth = 185
          ExplicitHeight = 89
        end
      end
    end
  end
end
