//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menumate.WinServices.Implementation.Contracts.DTO
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOLocation", Namespace="http://schemas.datacontract.org/2004/07/Menumate.WinServices.Implementation.Contr" +
        "acts.DTO")]
    public partial class DTOLocation : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte[] BackgroundImgField;
        
        private System.TimeSpan DefaultDurationField;
        
        private double HeightField;
        
        private int IdField;
        
        private string NameField;
        
        private Menumate.WinServices.Implementation.Contracts.DTO.DTOReservable[] ReservableListField;
        
        private Menumate.WinServices.Implementation.Contracts.DTO.DTOSession[] SessionsField;
        
        private double WidthField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BackgroundImg
        {
            get
            {
                return this.BackgroundImgField;
            }
            set
            {
                this.BackgroundImgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan DefaultDuration
        {
            get
            {
                return this.DefaultDurationField;
            }
            set
            {
                this.DefaultDurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Menumate.WinServices.Implementation.Contracts.DTO.DTOReservable[] ReservableList
        {
            get
            {
                return this.ReservableListField;
            }
            set
            {
                this.ReservableListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Menumate.WinServices.Implementation.Contracts.DTO.DTOSession[] Sessions
        {
            get
            {
                return this.SessionsField;
            }
            set
            {
                this.SessionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Width
        {
            get
            {
                return this.WidthField;
            }
            set
            {
                this.WidthField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOReservable", Namespace="http://schemas.datacontract.org/2004/07/Menumate.WinServices.Implementation.Contr" +
        "acts.DTO")]
    public partial class DTOReservable : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool AvailableField;
        
        private int CurrentInterestLevelField;
        
        private double HeightField;
        
        private int IdField;
        
        private int MaxGuestsField;
        
        private string NameField;
        
        private Menumate.WinServices.Implementation.Contracts.DTO.DTOLocation ParentLocationField;
        
        private double RotationAngleField;
        
        private string ShapeField;
        
        private string TableColorField;
        
        private double WidthField;
        
        private double XField;
        
        private double YField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Available
        {
            get
            {
                return this.AvailableField;
            }
            set
            {
                this.AvailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentInterestLevel
        {
            get
            {
                return this.CurrentInterestLevelField;
            }
            set
            {
                this.CurrentInterestLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxGuests
        {
            get
            {
                return this.MaxGuestsField;
            }
            set
            {
                this.MaxGuestsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Menumate.WinServices.Implementation.Contracts.DTO.DTOLocation ParentLocation
        {
            get
            {
                return this.ParentLocationField;
            }
            set
            {
                this.ParentLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double RotationAngle
        {
            get
            {
                return this.RotationAngleField;
            }
            set
            {
                this.RotationAngleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shape
        {
            get
            {
                return this.ShapeField;
            }
            set
            {
                this.ShapeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableColor
        {
            get
            {
                return this.TableColorField;
            }
            set
            {
                this.TableColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Width
        {
            get
            {
                return this.WidthField;
            }
            set
            {
                this.WidthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double X
        {
            get
            {
                return this.XField;
            }
            set
            {
                this.XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Y
        {
            get
            {
                return this.YField;
            }
            set
            {
                this.YField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOSession", Namespace="http://schemas.datacontract.org/2004/07/Menumate.WinServices.Implementation.Contr" +
        "acts.DTO")]
    public partial class DTOSession : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.TimeSpan EndTimeField;
        
        private int IdField;
        
        private bool IsInSessionField;
        
        private string NameField;
        
        private System.TimeSpan StartTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInSession
        {
            get
            {
                return this.IsInSessionField;
            }
            set
            {
                this.IsInSessionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPosIntegration")]
public interface IPosIntegration
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosIntegration/GetAllLocations", ReplyAction="http://tempuri.org/IPosIntegration/GetAllLocationsResponse")]
    Menumate.WinServices.Implementation.Contracts.DTO.DTOLocation[] GetAllLocations();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosIntegration/GetTablesForLocation", ReplyAction="http://tempuri.org/IPosIntegration/GetTablesForLocationResponse")]
    Menumate.WinServices.Implementation.Contracts.DTO.DTOReservable[] GetTablesForLocation(int locationId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosIntegration/GetBackgroundImgDataForLocation", ReplyAction="http://tempuri.org/IPosIntegration/GetBackgroundImgDataForLocationResponse")]
    byte[] GetBackgroundImgDataForLocation(int locationid);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IPosIntegrationChannel : IPosIntegration, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class PosIntegrationClient : System.ServiceModel.ClientBase<IPosIntegration>, IPosIntegration
{
    
    public PosIntegrationClient()
    {
    }
    
    public PosIntegrationClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PosIntegrationClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PosIntegrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PosIntegrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Menumate.WinServices.Implementation.Contracts.DTO.DTOLocation[] GetAllLocations()
    {
        return base.Channel.GetAllLocations();
    }
    
    public Menumate.WinServices.Implementation.Contracts.DTO.DTOReservable[] GetTablesForLocation(int locationId)
    {
        return base.Channel.GetTablesForLocation(locationId);
    }
    
    public byte[] GetBackgroundImgDataForLocation(int locationid)
    {
        return base.Channel.GetBackgroundImgDataForLocation(locationid);
    }
}
