//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4963
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenumateServices.DTO
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTODevice", Namespace="http://schemas.datacontract.org/2004/07/MenumateServices.DTO")]
    public partial class DTODevice : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressField;
        
        private uint IDField;
        
        private ushort PortField;
        
        private ushort TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort Port
        {
            get
            {
                return this.PortField;
            }
            set
            {
                this.PortField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOResponse", Namespace="http://schemas.datacontract.org/2004/07/MenumateServices.DTO")]
    public partial class DTOResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ushort CodeField;
        
        private uint DeviceIDField;
        
        private string MsgField;
        
        private MenumateServices.DTO.DTOPrompt[] PromptListField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint DeviceID
        {
            get
            {
                return this.DeviceIDField;
            }
            set
            {
                this.DeviceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Msg
        {
            get
            {
                return this.MsgField;
            }
            set
            {
                this.MsgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MenumateServices.DTO.DTOPrompt[] PromptList
        {
            get
            {
                return this.PromptListField;
            }
            set
            {
                this.PromptListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOPrompt", Namespace="http://schemas.datacontract.org/2004/07/MenumateServices.DTO")]
    public partial class DTOPrompt : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ushort CodeField;
        
        private string MsgField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Msg
        {
            get
            {
                return this.MsgField;
            }
            set
            {
                this.MsgField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWCFServiceEFTPOS")]
public interface IWCFServiceEFTPOS
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceEFTPOS/useDevice", ReplyAction="http://tempuri.org/IWCFServiceEFTPOS/useDeviceResponse")]
    MenumateServices.DTO.DTOResponse useDevice(MenumateServices.DTO.DTODevice inDeviceDTO);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceEFTPOS/status", ReplyAction="http://tempuri.org/IWCFServiceEFTPOS/statusResponse")]
    MenumateServices.DTO.DTOResponse[] status(MenumateServices.DTO.DTODevice[] inDeviceDTOList);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IWCFServiceEFTPOSChannel : IWCFServiceEFTPOS, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class WCFServiceEFTPOSClient : System.ServiceModel.ClientBase<IWCFServiceEFTPOS>, IWCFServiceEFTPOS
{
    
    public WCFServiceEFTPOSClient()
    {
    }
    
    public WCFServiceEFTPOSClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WCFServiceEFTPOSClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WCFServiceEFTPOSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WCFServiceEFTPOSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public MenumateServices.DTO.DTOResponse useDevice(MenumateServices.DTO.DTODevice inDeviceDTO)
    {
        return base.Channel.useDevice(inDeviceDTO);
    }
    
    public MenumateServices.DTO.DTOResponse[] status(MenumateServices.DTO.DTODevice[] inDeviceDTOList)
    {
        return base.Channel.status(inDeviceDTOList);
    }
}
