//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMateTests.WebMateWCFRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebMateWCFRef.IWCFServiceWebMate")]
    public interface IWCFServiceWebMate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceWebMate/OpenWebOrder", ReplyAction="http://tempuri.org/IWCFServiceWebMate/OpenWebOrderResponse")]
        MenumateServices.WebMate.DTO.DTO_WebOrderResponse OpenWebOrder(out string outHandle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceWebMate/CommitOrder", ReplyAction="http://tempuri.org/IWCFServiceWebMate/CommitOrderResponse")]
        MenumateServices.WebMate.DTO.DTO_WebOrderResponse CommitOrder(string inOrderHandle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceWebMate/SaveIncompleteOrderHeaderSection", ReplyAction="http://tempuri.org/IWCFServiceWebMate/SaveIncompleteOrderHeaderSectionResponse")]
        MenumateServices.WebMate.DTO.DTO_WebOrderResponse SaveIncompleteOrderHeaderSection(string inOrderHandle, MenumateServices.WebMate.DTO.DTO_WebOrderHeader inOrderHeaderSection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceWebMate/SaveIncompleteOrderFromSection", ReplyAction="http://tempuri.org/IWCFServiceWebMate/SaveIncompleteOrderFromSectionResponse")]
        MenumateServices.WebMate.DTO.DTO_WebOrderResponse SaveIncompleteOrderFromSection(string inOrderHandle, MenumateServices.WebMate.DTO.DTO_WebOrderFrom inOrderFromSection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceWebMate/SaveIncompleteOrderAccountSection", ReplyAction="http://tempuri.org/IWCFServiceWebMate/SaveIncompleteOrderAccountSectionResponse")]
        MenumateServices.WebMate.DTO.DTO_WebOrderResponse SaveIncompleteOrderAccountSection(string inOrderHandle, MenumateServices.WebMate.DTO.DTO_WebOrderAccount intOrderAccountSection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceWebMate/RetrieveIncompleteOrderHeaderSection", ReplyAction="http://tempuri.org/IWCFServiceWebMate/RetrieveIncompleteOrderHeaderSectionRespons" +
            "e")]
        MenumateServices.WebMate.DTO.DTO_WebOrderResponse RetrieveIncompleteOrderHeaderSection(out MenumateServices.WebMate.DTO.DTO_WebOrderHeader outHeaderSection, string inOrderHandle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceWebMate/RetrieveIncompleteOrderFromSection", ReplyAction="http://tempuri.org/IWCFServiceWebMate/RetrieveIncompleteOrderFromSectionResponse")]
        MenumateServices.WebMate.DTO.DTO_WebOrderResponse RetrieveIncompleteOrderFromSection(out MenumateServices.WebMate.DTO.DTO_WebOrderFrom outFromSection, string inOrderHandle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceWebMate/RetrieveIncompleteOrderAccountSection", ReplyAction="http://tempuri.org/IWCFServiceWebMate/RetrieveIncompleteOrderAccountSectionRespon" +
            "se")]
        MenumateServices.WebMate.DTO.DTO_WebOrderResponse RetrieveIncompleteOrderAccountSection(out MenumateServices.WebMate.DTO.DTO_WebOrderAccount outAccountSection, string inOrderHandle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceWebMate/GetCommittedWebOrderStatus", ReplyAction="http://tempuri.org/IWCFServiceWebMate/GetCommittedWebOrderStatusResponse")]
        MenumateServices.WebMate.DTO.DTO_WebOrderResponse GetCommittedWebOrderStatus(out MenumateServices.WebMate.DTO.WebOrderStatus outStatus, string inSiteName, string inStoreName, string inOrderHandle);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFServiceWebMateChannel : WebMateTests.WebMateWCFRef.IWCFServiceWebMate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFServiceWebMateClient : System.ServiceModel.ClientBase<WebMateTests.WebMateWCFRef.IWCFServiceWebMate>, WebMateTests.WebMateWCFRef.IWCFServiceWebMate {
        
        public WCFServiceWebMateClient() {
        }
        
        public WCFServiceWebMateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFServiceWebMateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceWebMateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceWebMateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MenumateServices.WebMate.DTO.DTO_WebOrderResponse OpenWebOrder(out string outHandle) {
            return base.Channel.OpenWebOrder(out outHandle);
        }
        
        public MenumateServices.WebMate.DTO.DTO_WebOrderResponse CommitOrder(string inOrderHandle) {
            return base.Channel.CommitOrder(inOrderHandle);
        }
        
        public MenumateServices.WebMate.DTO.DTO_WebOrderResponse SaveIncompleteOrderHeaderSection(string inOrderHandle, MenumateServices.WebMate.DTO.DTO_WebOrderHeader inOrderHeaderSection) {
            return base.Channel.SaveIncompleteOrderHeaderSection(inOrderHandle, inOrderHeaderSection);
        }
        
        public MenumateServices.WebMate.DTO.DTO_WebOrderResponse SaveIncompleteOrderFromSection(string inOrderHandle, MenumateServices.WebMate.DTO.DTO_WebOrderFrom inOrderFromSection) {
            return base.Channel.SaveIncompleteOrderFromSection(inOrderHandle, inOrderFromSection);
        }
        
        public MenumateServices.WebMate.DTO.DTO_WebOrderResponse SaveIncompleteOrderAccountSection(string inOrderHandle, MenumateServices.WebMate.DTO.DTO_WebOrderAccount intOrderAccountSection) {
            return base.Channel.SaveIncompleteOrderAccountSection(inOrderHandle, intOrderAccountSection);
        }
        
        public MenumateServices.WebMate.DTO.DTO_WebOrderResponse RetrieveIncompleteOrderHeaderSection(out MenumateServices.WebMate.DTO.DTO_WebOrderHeader outHeaderSection, string inOrderHandle) {
            return base.Channel.RetrieveIncompleteOrderHeaderSection(out outHeaderSection, inOrderHandle);
        }
        
        public MenumateServices.WebMate.DTO.DTO_WebOrderResponse RetrieveIncompleteOrderFromSection(out MenumateServices.WebMate.DTO.DTO_WebOrderFrom outFromSection, string inOrderHandle) {
            return base.Channel.RetrieveIncompleteOrderFromSection(out outFromSection, inOrderHandle);
        }
        
        public MenumateServices.WebMate.DTO.DTO_WebOrderResponse RetrieveIncompleteOrderAccountSection(out MenumateServices.WebMate.DTO.DTO_WebOrderAccount outAccountSection, string inOrderHandle) {
            return base.Channel.RetrieveIncompleteOrderAccountSection(out outAccountSection, inOrderHandle);
        }
        
        public MenumateServices.WebMate.DTO.DTO_WebOrderResponse GetCommittedWebOrderStatus(out MenumateServices.WebMate.DTO.WebOrderStatus outStatus, string inSiteName, string inStoreName, string inOrderHandle) {
            return base.Channel.GetCommittedWebOrderStatus(out outStatus, inSiteName, inStoreName, inOrderHandle);
        }
    }
}
