//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileMateTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileMateTests.TestResource", typeof(TestResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;FileMate&gt;
        ///  &lt;CopyGroup&gt;
        ///
        ///    &lt;CopyOperation name=&quot;summa&quot; deleteSource=&quot;false&quot; calledFromExternal=&quot;false&quot;&gt;
        ///      &lt;source url=&quot;c:\source\&quot;  /&gt;
        ///      &lt;targets&gt;
        ///        &lt;target url=&quot;c:\target\&quot;&gt;
        ///        &lt;/target&gt;
        ///      &lt;/targets&gt;
        ///
        ///      &lt;schedule&gt;1m&lt;/schedule&gt;
        ///
        ///      &lt;pattern&gt;*.dat&lt;/pattern&gt;
        ///
        ///    &lt;/CopyOperation&gt;
        ///
        ///  &lt;/CopyGroup&gt;
        ///&lt;/FileMate&gt;
        ///.
        /// </summary>
        internal static string FileMate_Test_Config {
            get {
                return ResourceManager.GetString("FileMate_Test_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;FileMate&gt;
        ///  &lt;CopyGroup&gt;
        ///
        ///    &lt;CopyOperation name=&quot;summa&quot; deleteSource=&quot;false&quot; calledFromExternal=&quot;false&quot;&gt;
        ///      &lt;source url=&quot;c:\source\&quot;  /&gt;
        ///      &lt;targets&gt;
        ///        &lt;target url=&quot;c:\target\&quot;&gt;
        ///        &lt;/target&gt;
        ///      &lt;/targets&gt;
        ///
        ///      &lt;schedule&gt;1m&lt;/schedule&gt;
        ///
        ///      &lt;pattern&gt;*.dat&lt;/pattern&gt;
        ///
        ///    &lt;/CopyOperation&gt;
        ///
        ///  &lt;/CopyGroup&gt;
        ///&lt;/FileMate&gt;
        ///.
        /// </summary>
        internal static string FileMateConfig_FilesToFolderWithSchedule {
            get {
                return ResourceManager.GetString("FileMateConfig_FilesToFolderWithSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;FileMate&gt;
        ///  &lt;CopyGroup&gt;
        ///
        ///    &lt;CopyOperation name=&quot;summa&quot; 
        ///                   deleteSource=&quot;true&quot;
        ///                   calledFromExternal=&quot;true&quot;
        ///                   &gt;
        ///
        ///      &lt;source url=&quot;c:\source\&quot; /&gt;
        ///
        ///      &lt;targets&gt;
        ///        &lt;target url=&quot;ftp://ftp.menumate.com/filematetarget/&quot;&gt;
        ///          &lt;credentials username=&quot;menumate&quot; password=&quot;menumate40&quot; /&gt;
        ///        &lt;/target&gt;
        ///        &lt;target url=&quot;c:\target\{date}\&quot; /&gt;
        ///      &lt;/targets&gt;
        ///
        ///      &lt;schedule&gt;5m&lt;/schedule&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileMateConfig_FilesToFtp {
            get {
                return ResourceManager.GetString("FileMateConfig_FilesToFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;FileMate&gt;
        ///  &lt;CopyGroup&gt;
        ///
        ///    &lt;CopyOperation name=&quot;summa&quot; deleteSource=&quot;true&quot; calledFromExternal=&quot;false&quot;&gt;
        ///
        ///      &lt;source url=&quot;c:\source\&quot; /&gt;
        ///
        ///      &lt;targets&gt;
        ///        &lt;target url=&quot;b:\bogus-target\&quot;&gt;
        ///
        ///        &lt;/target&gt;
        ///      &lt;/targets&gt;
        ///
        ///      &lt;schedule&gt;0m&lt;/schedule&gt;
        ///
        ///      &lt;pattern&gt;*.dat&lt;/pattern&gt;
        ///
        ///    &lt;/CopyOperation&gt;
        ///
        ///  &lt;/CopyGroup&gt;
        ///&lt;/FileMate&gt;
        ///.
        /// </summary>
        internal static string FileMateConfig_FileToFolderOfflineTarget {
            get {
                return ResourceManager.GetString("FileMateConfig_FileToFolderOfflineTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;FileMate&gt;
        ///  &lt;CopyGroup&gt;
        ///    &lt;CopyOperation name=&quot;download menu&quot; deleteSource=&quot;true&quot; calledFromExternal=&quot;false&quot;&gt;
        ///      &lt;source url=&quot;ftp://ftp.menumate.com/filematesource/&quot;&gt;
        ///        &lt;credentials username=&quot;menumate&quot; password=&quot;menumate40&quot; /&gt;
        ///      &lt;/source&gt;
        ///      &lt;targets&gt;
        ///        &lt;target url=&quot;C:\Program Files (x86)\MenuMate\Menu Import&quot; /&gt;
        ///      &lt;/targets&gt;
        ///      &lt;schedule&gt;5m&lt;/schedule&gt;
        ///      &lt;pattern&gt;*.test&lt;/pattern&gt;
        ///    &lt;/CopyOperation&gt;
        ///  &lt;/CopyGroup&gt;
        ///&lt;/FileMate&gt;.
        /// </summary>
        internal static string FileMateConfig_FtpToFolder {
            get {
                return ResourceManager.GetString("FileMateConfig_FtpToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;FileMate&gt;
        ///  &lt;CopyGroup&gt;
        ///
        ///    &lt;CopyOperation name=&quot;head office&quot;
        ///                   deleteSource=&quot;true&quot;
        ///                   calledFromExternal=&quot;false&quot;
        ///                   &gt;
        ///
        ///      &lt;source url=&quot;c:\source\&quot; /&gt;
        ///
        ///      &lt;targets&gt;
        ///        &lt;target url=&quot;ftp://ftp.menumate.com/filematetarget/site1/menus/&quot;&gt;
        ///          &lt;credentials username=&quot;menumate&quot; password=&quot;menumate40&quot; /&gt;
        ///        &lt;/target&gt;
        ///        &lt;target url=&quot;ftp://ftp.menumate.com/filematetarget/site2/menus/&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileMateConfig_HeadOfficeUpload {
            get {
                return ResourceManager.GetString("FileMateConfig_HeadOfficeUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;FileMate&gt;
        ///  &lt;CopyGroup&gt;
        ///
        ///    &lt;CopyOperation name=&quot;summa&quot; deleteSource=&quot;true&quot; calledFromExternal=&quot;false&quot;&gt;
        ///      &lt;source url=&quot;c:\source\&quot;  /&gt;
        ///      &lt;targets&gt;
        ///        &lt;target url=&quot;c:\target\&quot;&gt;
        ///        &lt;/target&gt;
        ///      &lt;/targets&gt;
        ///
        ///      &lt;schedule&gt;13:55&lt;/schedule&gt;
        ///
        ///      &lt;pattern&gt;*.dat&lt;/pattern&gt;
        ///
        ///    &lt;/CopyOperation&gt;
        ///
        ///  &lt;/CopyGroup&gt;
        ///&lt;/FileMate&gt;
        ///.
        /// </summary>
        internal static string FileMateTestConfig_scheduleSpecificTime {
            get {
                return ResourceManager.GetString("FileMateTestConfig_scheduleSpecificTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;FileMate&gt;
        ///	&lt;CopyGroup&gt;
        ///    &lt;CopyOperation name=&quot;summa&quot; deleteSource=&quot;false&quot; calledFromExternal=&quot;false&quot;&gt;
        ///      &lt;source url=&quot;c:\source\&quot; /&gt;
        ///      &lt;targets&gt;
        ///				&lt;target url=&quot;c:\target\{date}&quot;&gt;
        ///				&lt;/target&gt;
        ///			&lt;/targets&gt;
        ///      &lt;schedule&gt;0m&lt;/schedule&gt;
        ///      &lt;pattern&gt;*.dat&lt;/pattern&gt;
        ///    &lt;/CopyOperation&gt;
        ///	&lt;/CopyGroup&gt;
        ///&lt;/FileMate&gt;
        ///.
        /// </summary>
        internal static string TestConfig_FileToFolder {
            get {
                return ResourceManager.GetString("TestConfig_FileToFolder", resourceCulture);
            }
        }
    }
}
