#define xmlEleXMLVersion      ("XMLVersion")

#define xmlEleVersion           ("Version")
#define xmlAttrPOSVersion       ("POSVersion")
#define xmlAttrInterfaceVersion ("InterfaceVersion")

#define xmlEleProductVersion  ("ProductVersion")
#define xmlAttrVERSION        ("Version")
#define xmlAttrPRODUCT        ("Product")

#define xmlEleTerminal        ("Terminal")
#define xmlAttrID             ("id")
#define xmlAttrTerminalID     ("TerminalId")
#define xmlFileName           ("FileName")
#define xmlErr                ("ErrMsg")
#define xmlAttrXmlID          ("XmlID")
#define xmlAttrPLU            ("PLU")
#define xmlAttrTerminalName   ("TerminalName")
#define xmlAttrLocation       ("Location")
#define xmlAttrSiteID         ("SiteID")

#define xmlEleSender          ("Sender")
#define xmlAttrPayrollID      ("PayrollID")
#define xmlAttrName           ("Name")

#define xmlEleDestination     ("Destination")
#define xmlAttrTo             ("To")
#define xmlAttrFolio          ("Folio")

#define xmlEleReceipt          ("Receipt")
#define xmlAttrReceiptNo       ("ReceiptNumber")
#define xmlAttrTransactionType ("TransactionType")
#define xmlAttrDate            ("Date")
#define xmlAttrTime            ("Time")

#define xmlAttrTotalTendered   ("TotalTendered")
#define xmlAttrTotal						("Total")
#define xmlAttrTotalXTax            ("TotalXTax")
#define xmlAttrTotalTax             ("TotalTax")
#define xmlAttrAdjustment				("Adjustment")
#define xmlAttrAdjustmentXTax       ("AdjustmentXTax")
#define xmlAttrAdjustmentTax        ("AdjustmentTax")
#define xmlAttrTotalDiscount        ("Discount")
#define xmlAttrTotalSurcharge       ("Surcharge")
#define xmlAttrTotalSurchargeXTax   ("SurchargeXTax")
#define xmlAttrTotalSurchargeTax    ("SurchargeTax")
#define xmlAttrSummaGross           ("SummaGross")
#define xmlAttrSummaNet		         ("SummaNet")
#define xmlAttrSummaNetXTax         ("SummaNetXTax")
#define xmlAttrSummaNetTax          ("SummaNetTax")

#define xmlAttrTotalIncSurcharges ("TotalIncSurcharges")
#define xmlAttrTotalExcGST			("TotalExcGST")
#define xmlAttrGSTContent        ("GSTContent")
#define xmlAttrGSTPercent        ("GSTPercent")
#define xmlAttrGSTCost           ("GSTCost")
#define xmlAttrTotalPayment    ("TotalPayment")
#define xmlAttrTotalProduct    ("TotalProduct")

#define xmlAttrTotalSurcharges ("TotalSurcharges")

#define xmlElePayment          ("Payment")
#define xmlAttrCode            ("Code")
#define xmlAttrTotal           ("Total")
#define xmlAttrAmountTendered  ("Tendered")
#define xmlAttrAmountPay       ("Pay")
#define xmlAttrAmountChange    ("Change")
#define xmlAttrAmountCashOut   ("CashOut")
#define xmlAttrAmountSurcharge ("Surcharge")

#define xmlEleProduct         ("Product")
#define xmlAttrMenu           ("Menu")
#define xmlAttrCourse         ("Course")
#define xmlAttrItem           ("Item")
#define xmlAttrSize           ("Size")
#define xmlAttrQty            ("Qty")
#define xmlAttrServingCourse  ("ServingCourse")

#define xmlElePriceChanges    ("PriceChanges")
#define xmlElePriceChange     ("PriceChange")
#define xmlAttrReason         ("Reason")

#define xmlEleMetrics         ("Metrics")
#define xmlAttrLocation       ("Location")
#define xmlAttrGroupName      ("GroupName")
#define xmlAttrCategoryName   ("CategoryName")
#define xmlAttrGroupID        ("GroupID")
#define xmlAttrCategoryID     ("CategoryID")

#define xmlElePricing         ("Pricing")
#define xmlAttrAdjustmentTotal 			("AdjustmentTotal")
#define xmlAttrAdjustmentTotalExcGST 	("AdjustmentTotalExcGST")
#define xmlAttrAdjustmentGSTTotal 		("AdjustmentGSTTotal")
#define xmlAttrOrderType      ("OrderType")
#define xmlAttrHappyHour      ("HappyHour")
#define xmlAttrPointsRedeemed ("PointsRedeemed")
#define xmlAttrPointsPercent  ("PointsPercent")
#define xmlAttrPointsEarned   ("PointsEarned")
#define xmlAttrPriceLevel0    ("PriceLevel0")
#define xmlAttrPriceLevel1    ("PriceLevel1")


#define xmlEleSource          ("Source")
#define xmlAttrSource         ("Source")
#define xmlAttrTable          ("TableNo")
#define xmlAttrSeat           ("SeatNo")
#define xmlAttrRoom           ("RoomNo")
#define xmlAttrTab            ("TabName")
#define xmlAttrPax            ("Pax")

#define xmlEleRequest         ("Request")
#define xmlRequestType        ("Type")
#define xmlTypeStatus         ("Status")
#define xmlTypeEnquiry        ("Enquiry")
#define xmlTypeTransaction    ("Transaction")

#define xmlEleListPaymentTypes ("ListPaymentTypes")

#define xmlEleListProductTypes   ("ListProductTypes")
#define xmlMenuType              ("MenuType")
#define xmlMenuPalmable          ("Palmable")
#define xmlAttrSizes             ("Sizes")
#define xmlAttrSize              ("Size")
#define xmlEleServingCourses     ("ServingCourses")
#define xmlEleServingCourse      ("ServingCourse")
#define xmlAttrKitchenName       ("KitchenName")
#define xmlAttrApperanceOrder    ("AppearanceOrder")
#define xmlAttrSelectable        ("Selectable")
#define xmlAttrColour            ("Colour")
#define xmlAttrEnabled           ("Enabled")
#define xmlAttrDeleted           ("Deleted")
#define xmlEleCourses            ("Courses")
#define xmlEleCourse             ("Course")
#define xmlAttrDefaultServingCourse ("DefaultServingCourse")
#define xmlAttrDefault           ("Default")
#define xmlEleItems              ("Items")
#define xmlEleItem               ("Item")
#define xmlAttrExclusivelySide   ("ExclusivelySide")
#define xmlAttrPrice             ("Price")
#define xmlAttrCost              ("Cost")
#define xmlAttrMembSaleCount     ("MemberSaleCount")
#define xmlAttrMemDiscountPercent ("MemberDiscountPercent")
#define xmlAttrLocSaleCount      ("LocSaleCount")
#define xmlAttrLocDiscountPercent ("LocDiscountPercent")
#define xmlAttrTareWeight        ("TareWeight")
#define xmlAttrByWeight          ("ByWeight")
#define xmlAttrPrintChitNumber   ("PrintChitNumber")
#define xmlAttrDisplaySizes      ("DisplaySizes")
#define xmlEleFontInfo           ("FontInfo")
#define xmlAttrUnderLine         ("Underlined")
#define xmlAttrBold              ("Bold")
#define xmlAttrWidth             ("Width")
#define xmlAttrHight             ("Hight")
#define xmlAttrColour            ("Colour")
#define xmlAttrFont              ("Font")
#define xmlAttrGSTContent        ("GSTContent")
#define xmlAttrGSTPercent        ("GSTPercent")
#define xmlAttrBarCode           ("BarCode")
#define xmlAttrSpecialPrice      ("SpecialPrice")
#define xmlAttrAvailableAsStandard ("AvailableAsStandard")
#define xmlAttrSetMenuMask       ("SetMenuMask")
#define xmlAttrSetMenuMaster     ("SetMenuMaster")
#define xmlAttrSetMenuItem       ("SetMenuItem")
#define xmlEleRecipes            ("Recipes")
#define xmlEleRecipe             ("Recipe")
#define xmlAttrStockCode         ("StockCode")
#define xmlAttrStockLocation     ("StockLocation")
#define xmlAttrStockQty          ("StockQty")

#define xmlEleListCategories     ("ListCategories")
#define xmlEleCategories         ("Categories")
#define xmlEleCategoryGroups     ("CategoryGroups")
#define xmlEleCategory           ("Category")
#define xmlEleListGroups         ("ListGroups")
#define xmlEleListMemberGroups   ("ListMemberGroups")
#define xmlEleGroup              ("Group")

#define xmlEleListSummaGroups	 ("ListSummaGroups")

#define xmlAttrCategory          ("Category")
#define xmlEleCategory           ("Category")
#define xmlEleSides              ("Sides")
#define xmlEleSide               ("Side")
#define xmlAttrMasterItemXmlID   ("MasterItemXmlID")
#define xmlAttrItemXmlID         ("ItemXmlID")
#define xmlAttrGroupNumber       ("GroupNumber")

#define xmlEleOptions            ("Options")
#define xmlEleOption             ("Option")
#define xmlAttrMaxSelect         ("MaxSelect")
#define xmlAttrForcedMask        ("ForceMask")
#define xmlAttrFlags             ("Flags")
#define xmlAttrPlusOption        ("PlusOption")
#define xmlAttrMinusOption       ("MinusOption")
#define xmlAttrAllowSkip         ("AllowSkip")
#define xmlAttrMaxSelect         ("MaxSelect")


#define xmlEleListStaff          ("ListStaff")
#define xmlEleStaff              ("Staff")

#define xmlAttrTitle             ("Title")
#define xmlAttrSex               ("Sex")
#define xmlAttrFirstName         ("FirstName")
#define xmlAttrLastName          ("LastName")
#define xmlAttrMiddleName        ("MiddleName")
#define xmlAttrInitials          ("Initials")
#define xmlAttrLocation          ("Location")
#define xmlAttrMailing           ("Mailing")
#define xmlAttrPhone             ("Phone")
#define xmlAttrMobile            ("Mobile")
#define xmlAttrFax               ("Fax")
#define xmlAttrEmail             ("Email")
#define xmlAttrProxCard          ("ProxCard")
#define xmlAttrKnownAs           ("KnownAs")
#define xmlAttrDOB               ("DOB")
#define xmlAttrLastMod           ("LastMod")
#define xmlAttrLastVisit         ("LastVisit")
#define xmlAttrPayrollID         ("PayrollID")

#define xmlEleListDiscounts      ("ListDiscounts")
#define xmlEleDiscount           ("Discount")
#define xmlAttrMode              ("Mode")
#define xmlAttrType              ("Type")
#define xmlAttrDiscription       ("Discription")
#define xmlAttrPercent           ("Percent")
#define xmlAttrAmount            ("Amount")
#define xmlAttrRounding          ("Rounding")
#define xmlAttrPriority          ("Priority")

#define xmlEleTotalsPayments     ("TotalsPayments")
#define xmlAttrProperties        ("Properties")

#define xmlEleTotalsGroups       ("TotalsGroups")
#define xmlEleTotalsCategories   ("TotalsCategories")
#define xmlEleTotalsProducts     ("TotalsProducts")

#define xmlEleListCalculated     ("ListCalculated")
#define xmlEleTotalsDiscounts    ("TotalsDiscounts")
#define xmlEleTotalsCalculated   ("TotalsCalculated")
#define xmlEleCalculated         ("Calculated")
#define xmlEleTotalsStaff        ("TotalsStaff")
#define xmlEleTotalsPatron       ("TotalsPatron")
#define xmlEleListPatron         ("ListPatronTypes")
#define xmlElePatronType         ("PatronType")


#define xmlEleTotalsHourlySales  ("TotalsHourlySales")
#define xmlEleHour               ("Hour")

#define xmlEleMemberUpdate       ("UpdateMember")
#define xmlEleMember             ("Member")
#define xmlEleMemberSiteID       ("MemberSiteID")
#define xmlEleMemberXmlID        ("MemberXmlID")

#define xmlEleMagCards           ("MagCards")
#define xmlEleMagCard            ("MagCard")
#define xmlAttrCard              ("Card")
#define xmlAttrPoints            ("PointsTotal")
#define xmlAttrComp              ("CompTotal")
#define xmlAttrPromo2              ("Promo2Total")
#define xmlAttrPIN               ("AccessPIN")
#define xmlAttrAccessLevel       ("AccessLevel")
#define xmlAttrPalmAutoOpt       ("PalmAutoOpt")
#define xmlAttrPalmLgrFont       ("PalmLgrFont")
#define xmlAttrPalmAdvanced      ("PalmAdvanced")
#define xmlAttrPalmTimeOut       ("PalmTimeOut")
#define xmlAttrNextOrdNum        ("NextOrdNum")
#define xmlAttrOrderPrefix       ("OrderPrefix")
#define xmlAttrOrderSuffix       ("OrderSuffix")
#define xmlAttrPalmScnLock       ("PalmScnLock")
#define xmlAttrPalmClassic       ("PalmClassic")
#define xmlAttrPalmSndLevel      ("PalmSndLevel")
#define xmlAttrPalmAllTable      ("PalmAllTable")
#define xmlAttrMemNumber         ("MemNumber")
#define xmlAttrCrdCreateDate     ("CrdCreateDate")
#define xmlAttrNote              ("Note")
#define xmlAttrPointsRules       ("PointsRules")
#define xmlAttrAccName           ("AccName")
#define xmlAttrAccID             ("AccID")
#define xmlAttrThirdPartyKey     ("ThirdPartyCode")

#define xmlTimeClockInfo         ("TimeClock")
#define xmlAttrTimeStart         ("StartTime")
#define xmlAttrTimeEnd           ("EndTime")
#define xmlEleListRoster         ("ListRoster")
#define xmlTransNo 					("TransNo")

#define xmlAttrSummaGroup	 ("SummaGroup")

// WEb order defines
#define xmlEleOrdersResult ("OrderResult")
#define xmlEleOrders ("Orders")
#define xmlAttrOrderID ("OrderID")
#define xmlAttrStatus ("Status")
#define xmlMesg ("Msg")
#define xmlAttrAuth ("Authorised")
#define xmlRepeatTrans ("RepeatTranaction")



